### ISSUE TITLE
Long press menu is clipped 

### ISSUE THREAD

**Issue by johndoe422** [Deletescape-Media/Lawnchair#266] opened 2017-07-21 14:18 UTC
![screenshot_20170721-193741](https://user-images.githubusercontent.com/30309651/28467751-7e16b7ae-6e4e-11e7-873c-2ce768715e35.png)
Long press menu on app icons sometimes appears clipped, for example, check out the menu of Digitally Imported (DIFM) app's menu. 

This might be an existing issue, please duplicate and close it if it is already there.

**Comment by intelligentcasanova** [comment] 2017-07-21 14:48
Duplicate of #212

**Closed as completed** 2017-07-21 15:59 UTC
