### ISSUE TITLE
Bootloop on latest version with CM12.1

### ISSUE THREAD

**Issue by Haxk20** [Deletescape-Media/Lawnchair#386] opened 2017-08-02 20:06 UTC
Hi i installed latest version of this launcher 818 and after install and clicking home button system froze and restarted and was in bootloop i had to restore nandroid backup i tried the same apk on 6.0 and it was working ok.

**Comment by nyancrimew** [comment] 2017-08-03 06:47
1. I don't think this is directly related to Lawnchair
2. Without Logs or anything we can't do anything about this, as we have almost no chance to reproduce this

Closing this for now, if you can provide a log and can reproduce this we can reopen it

**Closed as completed by nyancrimew** 2017-08-03 06:47 UTC

**Comment by Haxk20** [comment] 2017-08-23 18:48
Well I have found the source of the problem seems like the Gradle 3.0.0 beta don't like 5.1.1 and crashes it totally I have tried this on another app and it worked so if you can please change Gradle to 2.7.7 it will be great.

**Comment by nyancrimew** [comment] 2017-08-23 20:10
If this is the issue you can compile your own custom builds using an older gradle plugin version. We will not change Android Studio and Gradle Plugin versions for unique issues

**Comment by Haxk20** [comment] 2017-08-26 21:18
dont you think i have tried that 
it gives me lot of errors at implement lines in build.gradle

**Comment by brainvision** [comment] 2017-09-21 09:52
I have this too. All cm 12.1 are definitely interested by this big issue. If you are not interested into solving it at least you should add something into the manifest so that those users could not install the launcher. Issue is serious because it causes bootloop! Most users don't know that they can simply remove Lawnchair folders and stuff from /data subfolders so they reset the device!
I also reported this into the XDA thread but no reply at all

**Comment by ildar** [comment] 2017-09-21 11:33
I am sorry, I agree with the dev this isn't Lawnchair-related. Just as the
"workaround" just boot in Safe mode and uninstall Lawnchair. Let us know if
this resolves the issue.

**Comment by brainvision** [comment] 2017-09-21 18:33
the problem for me personally is not how to unistall it because as I wrote I'm able to delete lawnchair stuff from recovery and then the device is able to boot again..
It's just that I tried it on others devices and I love it so I would like to use it on my CM 12.1 too! ;)

**Comment by ghost** [comment] 2017-10-27 00:30
https://issuetracker.google.com/issues/64434571
Hopefully updating build-tools will now fix the issue.

**Comment by Haxk20** [comment] 2017-10-28 17:05
Yes bug fixed in build tools 27 great.
@deletescape could you please update the app with this build tools ?

**Comment by Haxk20** [comment] 2017-10-28 17:16
OK sorry you already updated to that version great

**Comment by Haxk20** [comment] 2017-10-28 17:33
Confirming that latest version now works ! Finally Google you fixed it after 2 months.
