### ISSUE TITLE
[Feature Request] Icon search option. 

### ISSUE THREAD

**Issue by atul0000** [Deletescape-Media/Lawnchair#1299] opened 2018-07-08 11:16 UTC
Kindly add an option of searching Icons while changing any specific App's icon. It'll be easier & convenient for us to choose the icons or change the icons.
As well as add and option of lock desktop. So, it'll locked as like earlier v1 lawnchair.

**Comment by weirdeep** [comment] 2018-07-14 16:46
Very genuine demand.

**Comment by AxiK101** [comment] 2018-07-16 20:19
This should be a standard

**Comment by ghost** [comment] 2018-10-10 13:01
Duplicate of https://github.com/LawnchairLauncher/Lawnchair/issues/665?

**Comment by paphonb** [comment] 2018-10-10 14:10
Duplicate of #665.

**Closed as completed** 2018-10-10 14:10 UTC
