### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#555] opened 2017-08-19 16:56 UTC
Add the ability to choose an accent colour for the app drawer. The automatic colour pick from the wallpaper is useful, but i'd like that colour to stay even if i change my wallpaper. 
I'm sorry if it's a duplicate, could not check if It has been posted already.

**Comment by a220** [comment] 2017-08-20 01:18
Yeah I'm suprised this isn't a feature. I'd like love a custom color option

**Comment by suphon-t** [comment] 2017-08-20 13:12
Duplicate of #453. 
There is a button called "search"

**Closed as completed by suphon-t** 2017-08-20 13:12 UTC
