### ISSUE TITLE
[BUG] Using lawnicons doesnt change icons in recents

### ISSUE THREAD

**Issue by yavko** [Deletescape-Media/Lawnchair#2904] opened 2022-09-03 19:58 UTC
### Describe the bug

Using lawnicons doesn't change the icons in the recents menu

### Steps to reproduce

1. Use lawnicons
2. Open recents

### Expected behavior

Normally when choosing a custom icon for an app, the icon also changes in recents, but this doesnt happen when using lawnicons

### Screenshots

![Screenshot_20220903-125831_Calculator](https://user-images.githubusercontent.com/15178513/188286007-a11bac96-591f-4a3d-b3dd-c0a40ee633e1.png)

### Device information

- Device: Razer Phone 2 aka aura
- OS: lineage 19.1
- App version: 12.1.0 alpha 3

**Comment by SuperDragonXD** [comment] 2022-09-04 05:37
Duplicate of #2790

**Closed as not planned by SuperDragonXD** 2022-09-04 05:37 UTC
Labels: bug

**Comment by yavko** [comment] 2022-09-04 05:44
> Duplicate of #2790

Couldn't find the issue sorry!
