### ISSUE TITLE
[BUG] Search results do not clear when quickly deleting search entry

### ISSUE THREAD

**Issue by tgex0** [Deletescape-Media/Lawnchair#4819] opened 2024-09-14 13:55 UTC
### Describe the bug

After searching in the app drawer and deleting the search query one character at a time, the search results are empty when the search query has been completely deleted (OK so far).
However, if the search query is deleted quickly by holding down the backspace key, the search results show the results for the first letter of the original search (even though the search bar is now empty).

### Steps to reproduce

1. Go to 'Drawer search -> Search algorithm'
2. Select 'Global search (on-device)' and make sure that 'Apps & Shortcuts' and 'Web suggestions' are selected
3. Go to the app drawer and type in a longish search query (not just one or two characters) e.g. "Lightroom"
4. Hold down backspace key until search query is complete deleted
5. Search results still show results for "L" (see screenshot)

It seems important that 'Web suggestions' is selected. This bug does not happen when 'Drawer search -> Search algorithm -> App Search' is selected.

### Expected behavior

I would expect the app drawer search to not show the results of a search when the search bar is empty.

### Screenshots

![1726321895452](https://github.com/user-attachments/assets/078e2a4b-8b14-443c-a67c-5608deb574ad)

### Device information

- Device: POCO X5 5G
- OS: HyperOS 1.0.8.0 (stock, Android 14)
- App version: Lawnchair 14.Dev.(d7e3f32) (Play Store version) and current dev source (GitHub c1108ae)

**Comment by MrSluffy** [comment] 2024-12-15 02:01
this is not a bug it's normal behaviour same as pixel launcher closing this create an issue as feature request instead

**Closed as completed by MrSluffy** 2024-12-15 02:01 UTC
Labels: bug

**Comment by tgex0** [comment] 2024-12-15 03:27
> this is not a bug it's normal behaviour same as pixel launcher closing this create an issue as feature request instead

Fair enough. If this is not a bug, I see no reason to deviate from standard Pixel Launcher behavior. Thanks!
