### ISSUE TITLE
Make custom page main page instead of leftest

### ISSUE THREAD

**Issue by Stanzi97** [Deletescape-Media/Lawnchair#1204] opened 2018-04-04 16:40 UTC
## Description
Basically, the ttle says it all, but I'll go through this guided bug-reporting procedure anyway.

## Expected Behavior
Some kind of setting where I can choose which of my pages is the main page where I get if I presse home while already in the launcher.

## Actual Behavior
The leftest page is always tha main page. I didn't find a way to change that

## Steps to Reproduce
Just tap on the home button while inside the launcher.

## Environment
* Fairphone 2
* Android 6.0.1
* Launcher version
* Rom: Fairphone Open (basically close to Stock Android, without the Google spywa... ehm... "software"

**Comment by nyancrimew** [comment] 2018-04-04 16:42
Duplicate of #308 and other issues

**Comment by Stanzi97** [comment] 2018-04-04 16:42
Sorry, I forgot to write that the Launcher version is 1.1.0.1872 which is the newest version available on GitHub on 4.4.2018.

**Closed as completed by nyancrimew** 2018-04-04 16:42 UTC

**Comment by divadsn** [comment] 2018-04-04 19:29
@Stanzi97 That's not the Pixel style, sorry :)

**Comment by ghost** [comment] 2018-05-06 07:17
Actually, it's not a question of style, it is a question of possibilities. More customization options = more satisfied users. Also, there can't be enough editing functions as well - inserting or at least reordering home screen pages is a very important part of this game.

I like this launcher, stable, and almost has the minimum feature set I need. :-) Struggling with changing to it, though. The most used layout by me is to have the default home screen (available by pressing the Home button again, as well) in the middle, this way the neighbor pages with more important widgets and icons can be reached faster than the neighbors of neighbor ones, and so on. There are things that just cannot be made better, only worse - at the expense of being followers, being similar to others in some topics, I admit.

**Comment by shubhchan** [comment] 2018-05-06 07:20
@ha3flt More customization option = more bugs and users complaints " MAH GWAD YER APP NU WORK, U POOR NOOB DEV"

**Comment by ghost** [comment] 2018-05-06 07:22
Yes, the truth is somewhere in the middle, I'm aware. I just tried to shift the reality to fit to me a bit better. :-)

**Comment by bohrabhijeet** [comment] 2018-05-06 07:22
@ha3flt Glad you understand ;)

**Comment by ghost** [comment] 2018-05-06 07:24
But as you can see, my opinion still is, that this exact feature improvement well worth the hassle.

**Comment by bohrabhijeet** [comment] 2018-05-06 07:26
@ha3flt I'll let the dev team know about this. Sure.

**Comment by divadsn** [comment] 2018-05-06 09:14
@ha3flt in our opinion it is a style choice, as we are not Nova Launcher where you can have whatever you want. Take a look for example at ASAP Launcher, where your left and right pages are set to weather, agenda or contacts as well.
