### ISSUE TITLE
Browsers can't add site shortcuts.

### ISSUE THREAD

**Issue by arttuc** [Deletescape-Media/Lawnchair#1988] opened 2020-04-28 12:03 UTC
## Description

When i try to add a site shortcut from my browser (Firefox Preview Nightly), the shortcut appears for a second and then dissapears.
I also tried this with google chrome, same result.

## Expected Behavior

The shortcut would stay on the homescreen.

## Actual Behavior

The shortcut dissapears or doesn't go in the homescreen at all.

## Steps to Reproduce

1. Open Firefox Preview or Chrome
2. Go to any website
3. Open the menu and click 'Add to homescreen' (or something similar, my language is finnish so i don't know)
![1](https://user-images.githubusercontent.com/37794543/80485007-5474df80-8961-11ea-815c-7168ffc4219a.png)
4. Click 'Add automatically' or drag the icon.
![2](https://user-images.githubusercontent.com/37794543/80485004-5343b280-8961-11ea-8b76-7dcaf8acfbbd.png)

## Environment

* Device: Poco F1 "beryllium"
* Android version: 10
* Launcher version: 2.1-2621-ci-q-merge
* Rom: LineageOS 17.1-20200404-NIGHTLY-beryllium

**Comment by sinus-x** [comment] 2020-06-16 13:06
Duplicate of #1903

**Comment by RikKoedoot** [comment] 2021-08-27 11:31
Closing because effort has been moved to v11

**Closed as completed by RikKoedoot** 2021-08-27 11:31 UTC
