### ISSUE TITLE
In Lenovo K6 theres no on-screen nav bar, but when choosing widget its black inthat area, plz fix that

### ISSUE THREAD

**Issue by ArmanKir-yan25** [Deletescape-Media/Lawnchair#504] opened 2017-08-12 21:49 UTC
![Uploading Screenshot_20170813-014601.jpeg…]()
![screenshot_2017-08-13-01-47-18-837](https://user-images.githubusercontent.com/30963247/29244480-91e72cf0-7fc9-11e7-8eb0-c12418b83665.jpeg)
![Uploading Screenshot_20170813-014604.jpeg…]()

**Comment by suphon-t** [comment] 2017-08-13 03:23
Duplicate of #358

**Closed as completed by suphon-t** 2017-08-13 03:23 UTC
