### ISSUE TITLE
Lawnchair Bug and A Question.

### ISSUE THREAD

**Issue by omekurnia** [Deletescape-Media/Lawnchair#1105] opened 2018-01-02 08:42 UTC
Hello, thanks for your awesome job at Lawnchair Launcher. I use it as my daily launcher as i am testing my icon pack.

I just found a bug and unable to reproduce it. The bug is you can not press and hold at home screen in order to open wallpaper-widget-setting.

And a question. How to put Lawnchair on apply section at my icon pack?

Thanks for your response. Have a good day!

**Comment by Frontear** [comment] 2018-02-07 15:48
Firstly, steps to reproduce the bug must be given, otherwise the bug cannot be traced back. This issue does not occur for me, and I don't believe others have this issue. You should try to use the latest version of lawnchair and see if the issue persists. If it  does, report your device model with the version of android you are running. Second, if you want to add lawnchair to your icon pack application, you must ask the developer of the icon pack.

**Comment by divadsn** [comment] 2018-02-07 15:55
To correct you, @Frontear, that unresponsive press and hold bug is well-known and it's caused by the new way to restart Lawnchair, but we won't fix it as we are going to work on v2, where we will make the settings work without a restart.

Same goes with the second question, we will add a way in v2, I first have to get how other Launchers do the "apply" action callback for iconpacks.

**Comment by Frontear** [comment] 2018-02-07 15:58
Thank you for the correction @divadsn
It had not occured to me that such a bug exists, as I have *never* experienced it before.

**Comment by divadsn** [comment] 2018-02-07 15:59
@Frontear Happens a lot only when you change settings a lot ;)

**Comment by omekurnia** [comment] 2018-02-09 10:41
hi @Frontear @divadsn thank you guys for your response ;)

I'll be waiting in excitement for v2 release. Like @divadsn said, it is exist and for me the bug rarely appear. I always forgot to take the screenshot because I just restarted my phone to quickly fix it.

And for the apply, maybe @Frontear did not really know why I asked it on the first place. I really hope you guys provide it on the v2 so we have another to represent our icon pack instead of 'Nova' *wink*.

**Closed as completed** 2018-03-27 16:40 UTC
