### ISSUE TITLE
"Detected problems with app native libraries...."

### ISSUE THREAD

**Issue by JackGitrocks-19** [Deletescape-Media/Lawnchair#610] opened 2017-08-26 06:20 UTC
Hello, Huge fan of your work!
I'm using the latest version (26/08).....There's a dialog on startup of launcher saying "Detected problems with app native libraries--->>libavcodec.so:text relocation, libswresample.so:text relocations..."

Can you please look into this issue and fix it.....I guess this issue is present in most Asus x86 devices
[I'm running LineageOS 14.1 builds in my Asus Zenfone 2(Z00A--->x86)]

**Comment by suphon-t** [comment] 2017-08-26 09:34
Duplicate of #119

**Closed as completed by suphon-t** 2017-08-26 09:34 UTC
