### ISSUE TITLE
Lawnchair 11 crash on OneUI 3.1

### ISSUE THREAD

**Issue by luke-apk** [Deletescape-Media/Lawnchair#2115] opened 2021-03-29 14:20 UTC
S21 Ultra 5G (SM-G998B) I had tested it on but force closes on launch

**Comment by AgentFabulous** [comment] 2021-03-29 14:23
> S21 Ultra 5G (SM-G998B) I had tested it on but force closes on launch

Thanks for the report! Could you pull a logcat?

**Comment by AntoineQ1** [comment] 2021-04-09 07:59
I had this problem. I changed the navigation bar to default mode since it was in gesture mode and it worked again. I just put it back to gesture mode and it seems to work, maybe not for long. The problem is probably linked with the navigation bar.

**Comment by luke-apk** [comment] 2021-04-10 11:51
> I had this problem. I changed the navigation bar to default mode since it was in gesture mode and it worked again. I just put it back to gesture mode and it seems to work, maybe not for long. The problem is probably linked with the navigation bar.

Just saw that it's related to samsung's specific gesture mode as if you switch to google's gesture method on OneUI it doesn't crash - will try to obtain log for this

**Comment by luke-apk** [comment] 2021-04-10 12:01
[lawnchair-11-alpha-oneui3-g977b.zip](https://github.com/LawnchairLauncher/lawnchair/files/6289780/lawnchair-11-alpha-oneui3-g977b.zip)

**Comment by luke-apk** [comment] 2021-04-10 12:01
> > S21 Ultra 5G (SM-G998B) I had tested it on but force closes on launch
> 
> Thanks for the report! Could you pull a logcat?

Logcat posted above

**Comment by cj81499** [comment] 2021-05-06 03:23
Just writing to say that I have the same problem. Hoping this is fixed soon. 🙂

**Comment by aozora-tori** [comment] 2021-08-21 03:39
sorry to bump this, but even at alpha 6, lawnchair seems to crash on One UI 3.1 — especially on the three-button gesture navigation

**Comment by RikKoedoot** [comment] 2021-08-21 06:04
You can disable gestures, open lawnchair, and enable gestures again. This is a workaround for untill we fix it

**Comment by RikKoedoot** [comment] 2021-08-27 11:06
Closing as it should be fixed in the coming update

**Closed as completed by RikKoedoot** 2021-08-27 11:06 UTC
Labels: bug

**Comment by cj81499** [comment] 2021-08-27 16:16
Working for me. Thank you!
