### ISSUE TITLE
Microphone icon instead Assistant one

### ISSUE THREAD

**Issue by MicheleLele** [Deletescape-Media/Lawnchair#515] opened 2017-08-13 12:35 UTC
Hi there, can you add a toggle for showing the microphone icon on the Google pill widget instead the Assistant one? Thanks for the attention.

![1](https://user-images.githubusercontent.com/24496956/29249669-85eee968-8034-11e7-956b-959cd7e64833.png)

**Comment by suphon-t** [comment] 2017-08-14 00:36
Duplicate of #369

**Closed as completed by suphon-t** 2017-08-14 00:36 UTC
