### ISSUE TITLE
Calling UI problem

### ISSUE THREAD

**Issue by nimaarya** [Deletescape-Media/Lawnchair#1519] opened 2019-04-20 19:49 UTC
my new phone came by recent Android pie gestures, the only problem I've got with lawnchair is that whenever i come from any app to home screen using no navigation bar gestures, and then open phone app to call sb, call ui disappears and screen goes back to home screen, I've tested it with default launcher, no problems, and then i enabled navigation bar and tested lawnchair, again no problems at all. so...
thanks for your time...

 Device: OnePlus 6t (A6010)
 Android version: 9
 Launcher version: 2.0-1957
 Rom: OxygenOs

**Comment by snehjogani** [comment] 2019-04-21 05:07
@nimaarya  I'm facing a similar issue. Along with taking me to the home screen on **making a call**, it does the same when **picking up a call** from lock screen.

Device: OnePlus 6
Android versino: 9
Launcher version: 2.0-1995-ci-alpha

**Comment by nimaarya** [comment] 2019-04-21 05:11
@snehjogani thats exactly the case.

**Comment by bohrabhijeet** [comment] 2019-04-21 05:21
@snehjogani @nimaarya This is something I haven't ever seen relating to a launcher. However, the developers will investigate and try to get to a solution ASAP. :)

**Comment by suphon-t** [comment] 2019-04-21 06:01
This issue is from the OnePlus Dialer app and happens on all 3rd party launchers. Closing now as it's not caused by Lawnchair and we can't fix it.

**Closed as completed by suphon-t** 2019-04-21 06:01 UTC
