### ISSUE TITLE
Search In App Drawer is cut off

### ISSUE THREAD

**Issue by SimplyAnotherAnon** [Deletescape-Media/Lawnchair#4546] opened 2024-07-06 06:17 UTC
### Describe the bug

The search results in the app drawer are cut off such that some searches cannot be accessed, this is especially the case and a major issue with hidden apps which cannot be accessed at all thru the search results when I have the setting for them to only appear in the search results enabled. 
In the screenshots below I've attached my settings for search as well as the issue itself

### Steps to reproduce

1. Go to app drawer 
2. Click on app search bar at top of drawer
3. Type in anything, but particularly the name of a hidden app
4. Be unable to click the hidden app due to the search results being cut off 

### Expected behavior

I should be able to view all expected search results especially hidden apps 

### Screenshots

![Screenshot_20240705-231304](https://github.com/LawnchairLauncher/lawnchair/assets/115472706/33b1bfaf-aa50-40ff-9da9-61b0024b26b7)
![Screenshot_20240705-231259](https://github.com/LawnchairLauncher/lawnchair/assets/115472706/c00070f4-6c6e-4be2-af3b-83e4918e62e5)
![Screenshot_20240705-230101](https://github.com/LawnchairLauncher/lawnchair/assets/115472706/94c5e46c-e1ca-45f3-a2a0-caa8ee01b2e5)
![Screenshot_20240705-230051](https://github.com/LawnchairLauncher/lawnchair/assets/115472706/6f77efe3-21f5-4de1-aff2-b549bf664f68)

### Device information

- Device: Google Pixel 8 Pro 
- OS: Stock Pixel Android 14 (AP2A.240605.024)
- App version: Latest Nightly July 5th Release

**Comment by HyperWinX** [comment] 2024-07-07 03:27
Same issue. Android 11

**Comment by Illustar0** [comment] 2024-07-09 09:29
Same issue. Android 14

**Comment by SuperDragonXD** [comment] 2024-07-09 09:53
Hey there,

I'm not sure what you mean by "cut off": is it the weird highlight, or is it the "no apps aside from hidden apps showing when searching"?

If it's the latter, please enable "Apps and Shortcuts" to search... your apps and shortcuts ._(I should probably hide the option of disabling that)_

Otherwise, that bug is fixed in my testing builds and will be pushed later.

**Comment by SimplyAnotherAnon** [comment] 2024-07-09 10:38
> Hey there,
> 
> I'm not sure what you mean by "cut off": is it the weird highlight, or is it the "no apps aside from hidden apps showing when searching"?
> 
> If it's the latter, please enable "Apps and Shortcuts" to search... your apps and shortcuts ._(I should probably hide the option of disabling that)_
> 
> Otherwise, that bug is fixed in my testing builds and will be pushed later.

As you can clearly see in the above screenshots I already sent, the search results are literally cut off at the top, meaning not all the search results that are supposed to be visible, are in fact visible. Not much more to explain. 

In the below screenshots, you can clearly see the app "Amazon" appearing in my normal app drawer, but if I type the app name into the search bar, I cannot open the app in the search results because it's **cut off**. 
![Screenshot_20240709-033620.png](https://github.com/LawnchairLauncher/lawnchair/assets/115472706/eee752dc-14de-4d6f-8f41-d81fd78455d7)
![Screenshot_20240709-033630.png](https://github.com/LawnchairLauncher/lawnchair/assets/115472706/f5d996b3-8e31-4adf-9c8c-ad9eadb312ac)

Another example, bitwarden:
![Screenshot_20240709-033936.png](https://github.com/LawnchairLauncher/lawnchair/assets/115472706/86179043-14d4-428d-9b0f-1a89b212100f)

Enabling apps and shortcuts does not resolve the issue at all.

**Comment by Unofficial-Life** [comment] 2024-07-10 09:17
Similar and related issues #4531 and #4538

suspected error are maybe caused by 71f807c

**Closed as completed** 2024-07-20 04:30 UTC
Labels: bug
