### ISSUE TITLE
Toggle To Move App Drawer Search At The Buttom Just Like Android 13 Pixel Launcher

### ISSUE THREAD

**Issue by Amorphous404** [Deletescape-Media/Lawnchair#2865] opened 2022-08-22 18:39 UTC
### Describe the feature

Toggle To Move App Drawer Search At The Buttom Just Like Android 13 Pixel Launcher

### Why would it be useful to add?

It Will Allow User To Easily Reach The App Drawer Search (One Had Friendly)

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_2022-08-23-00-02-01-60](https://user-images.githubusercontent.com/96917972/185994735-04e32ebd-cf55-469d-be83-548c1bbf4e88.jpg)

**Comment by SuperDragonXD** [comment] 2022-08-23 04:15
Duplicate of #2801

**Closed as completed by SuperDragonXD** 2022-08-23 04:15 UTC
Labels: enhancement, feature-request
