### ISSUE TITLE
[FEATURE] Іndents from the screen in the app menu

### ISSUE THREAD

**Issue by ArturMartic** [Deletescape-Media/Lawnchair#3868] opened 2023-12-17 11:34 UTC
### Describe the feature

indents from the screen in the application menu

### Why would it be useful to add?

so that the application menu is not stretched

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20231217_130700_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/152477013/8facdd53-5d17-4721-a257-42155caad901)

**Comment by avm99963** [comment] 2023-12-19 19:34
Maybe this is also related to the very little padding/indentation in the home screen (which is clearly seen when the search bar in the dock is disabled), as well as the smaller icons:

| Latest debug apk (commit [a2a84c2](https://github.com/LawnchairLauncher/lawnchair/commit/a2a84c2da672709fde22d7c6e2737b1a7a8f0640)) | Before ([Lawnchair 12.1.0 Alpha 4](https://github.com/LawnchairLauncher/lawnchair/releases/tag/v12.1.0-alpha.4)) |
| :---: | :---: |
| ![Screenshot_20231219-195814.png](https://github.com/LawnchairLauncher/lawnchair/assets/682310/4ad94dd2-569a-4548-affa-c4f5b2e6c12d) | ![Screenshot_20231219-200656.png](https://github.com/LawnchairLauncher/lawnchair/assets/682310/66d076bb-ed4a-4f3a-aac1-b8f951058a19) |

And it might also be related to the cropped icons when searching in the drawer:

![291691590-2ac2b4e8-b073-4fad-bffc-8291feda2845](https://github.com/LawnchairLauncher/lawnchair/assets/682310/396d4dc7-700b-4358-9097-cd88a0c1cb34)

I started noticing this when installing the 14-dev builds. Is the change in padding intended (due to a change in launcher3 or because you decided to do it) or a regression?

PS: I can also file these as separate issues if you prefer.

**Comment by MrSluffy** [comment] 2023-12-20 04:52
> Maybe this is also related to the very little padding/indentation in the home screen (which is clearly seen when the search bar in the dock is disabled), as well as the smaller icons:
> 
> Latest debug apk (commit [a2a84c2](https://github.com/LawnchairLauncher/lawnchair/commit/a2a84c2da672709fde22d7c6e2737b1a7a8f0640))	Before ([Lawnchair 12.1.0 Alpha 4](https://github.com/LawnchairLauncher/lawnchair/releases/tag/v12.1.0-alpha.4))
> ![Screenshot_20231219-195814.png](https://private-user-images.githubusercontent.com/682310/291687883-4ad94dd2-569a-4548-affa-c4f5b2e6c12d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDc5MjQsIm5iZiI6MTcwMzA0NzYyNCwicGF0aCI6Ii82ODIzMTAvMjkxNjg3ODgzLTRhZDk0ZGQyLTU2OWEtNDU0OC1hZmZhLWM0ZjViMmU2YzEyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwNDQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODc5MTQ3YmM3MzRjZmQwMTAzYzQ0OTVmYzk2MGE0ZDQxYmEyNTRmMTRlZjQ0ZmUxMjMwZDRhMjkzZTM3YzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TGp80KWhiTq1DpBwVT3zZvQdtAjzyZGZXxCr2jSWN-o)	![Screenshot_20231219-200656.png](https://private-user-images.githubusercontent.com/682310/291688943-66d076bb-ed4a-4f3a-aac1-b8f951058a19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDc5MjQsIm5iZiI6MTcwMzA0NzYyNCwicGF0aCI6Ii82ODIzMTAvMjkxNjg4OTQzLTY2ZDA3NmJiLWVkNGEtNGYzYS1hYWMxLWI4Zjk1MTA1OGExOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwNDQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzNkNTNiYjAyY2FjOTBmMTZjM2QyZmJlMzU0MjdkMmU0M2M4OThkM2NiYWM0OTZhNjc3Njk0M2VhZDFlZTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cmxCHwevXw05PDHqSjEDsqHAeTD8vTy7sdgBI4T4Lz4)
> And it might also be related to the cropped icons when searching in the drawer:
> 
> ![291691590-2ac2b4e8-b073-4fad-bffc-8291feda2845](https://private-user-images.githubusercontent.com/682310/291692140-396d4dc7-700b-4358-9097-cd88a0c1cb34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDc5MjQsIm5iZiI6MTcwMzA0NzYyNCwicGF0aCI6Ii82ODIzMTAvMjkxNjkyMTQwLTM5NmQ0ZGM3LTcwMGItNDM1OC05MDk3LWNkODhhMGMxY2IzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwNDQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2VkMDU2YWQwNzdiYjgxMTFjMjY3N2ZjNTJkZWNjNjU5MGNmNTMxNDNkOTQ2ZTczMzY2YWNkMDRhMTI3YTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SSs9dpvhqEhqlNTKdrHJCldd3I_JZzWIIVOHNmXS3Ww)
> 
> I started noticing this when installing the 14-dev builds. Is the change in padding intended (due to a change in launcher3 or because you decided to do it) or a regression?
> 
> PS: I can also file these as separate issues if you prefer.


**Yes please, create separate issue and label it as bug,** 
**UPDATE**
- Fixed now in #3897

**Closed as completed** 2023-12-27 00:06 UTC
Labels: enhancement, feature-request
