### ISSUE TITLE
Google Pill randomly disappears

### ISSUE THREAD

**Issue by gcladores** [Deletescape-Media/Lawnchair#516] opened 2017-08-13 12:40 UTC
When I go into an app and return to the launcher sometimes the Pill is gone. Or if I go into the settings os Lawnchair and gose back home it's gone. Then randomly returns again.

**Comment by AxiK101** [comment] 2017-08-13 13:07
Yes this is a pretty old bug indeed

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment] 2017-08-13 14:06
Duplicate of #112.

**Closed as completed** 2017-08-14 00:36 UTC
