### ISSUE TITLE
App shortcuts bubble bug

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#1135] opened 2018-02-02 15:51 UTC
## Description
The old edge line bug on bubbles. Is present on most screen dpis (not on default 360). This pic is in 330dpi.

## Expected Behavior
Not to show this line

## Actual Behavior
Most dpis shows this line in bubbles with enabled shortcuts (only)

## Steps to Reproduce

1. Change screen dpi
2. Check bubbles

## Environment

* Device: Xperia XA Ultra (F3211)
* Android version: 7.0
* Launcher version: 1.1.0.1834 (CI)
* Rom: 36.1.A.1.86 (Stock)

## Logcat

```
your log here
```

**Comment by AxiK101** [comment] 2018-02-02 15:52
![](https://i.imgur.com/sgf9y7R.png)

**Comment by divadsn** [comment] 2018-02-02 16:05
@AxiK101 Duplicate of issues, don't open new please.

**Closed as completed** 2018-02-17 17:00 UTC
