### ISSUE TITLE
Periodic lag / freezing

### ISSUE THREAD

**Issue by Arkanas1** [Deletescape-Media/Lawnchair#132] opened 2017-07-05 16:03 UTC
The launcher freezes when i hold on an app icon for the app shortcuts, then pressing the back button. It freezes for a few seconds before coming back to normal.

**Comment by tstackhouse** [comment] 2017-07-05 19:48
Possible duplicate of #76?

**Comment by vivekappas** [comment] 2017-07-09 13:12
Double tap to locking and unlocking screen in needed

**Comment by paphonbth** [comment] 2017-07-09 13:38
Duplicate of #76

**Closed by paphonbth** 2017-07-09 13:38 UTC
