### ISSUE TITLE
"app isn't installed" error when opening some apps

### ISSUE THREAD

**Issue by MarcusKulik** [Deletescape-Media/Lawnchair#2149] opened 2021-05-13 07:52 UTC
Pixel 5, android version 11 
Lawnchair version 2.0-2589

every time I launch certain, seemingly random, apps, I get a little bubble giving me an error "app isn't installed" at the bottom of the screen. The app opens and functions just fine, it clearly is installed. 

When I switch back to the default pixel launcher the issue goes away. 

this happens every time the app is opened but some apps have randomly stopped doing this and now open without throwing the error.

**Comment by jstewart** [comment] 2021-05-28 20:21
I receive the same message only AFTER I installed the most recent Android patches on my Pixel 5.

**Comment by mbuett** [comment] 2021-06-29 13:16
Same for me. Using Lawnchair on a Redmi Note 7 with LineageOS 18.1. Prior to using LOS 18 everything worked as expected.
I can reproduce it using the current version of [SlimSocial from F-Droid](https://f-droid.org/en/packages/it.rignanese.leo.slimfacebook/).

Logcat message while trying to open SlimSocial on current V11 alpha:
```
 E  Unable to launch. tag=AppInfo(id=-1 type=APP container=all_apps targetComponent=ComponentInfo{it.rignanese.leo.slimfacebook/it.rignanese.leo.slimfacebook.MainActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=SlimSocial componentName=ComponentInfo{it.rignanese.leo.slimfacebook/it.rignanese.leo.slimfacebook.MainActivity}) intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=it.rignanese.leo.slimfacebook/.MainActivity bnds=[25,1320][231,1660] }
 E  java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=it.rignanese.leo.slimfacebook/.MainActivity bnds=[25,1320][231,1660] } from ProcessRecord{188f51 22283:app.lawnchair/u0a245} (pid=22283, uid=10245) not exported from uid 10244
 E      at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
 E      at android.os.Parcel.createException(Parcel.java:2357)
 E      at android.os.Parcel.readException(Parcel.java:2340)
 E      at android.os.Parcel.readException(Parcel.java:2282)
 E      at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3696)
 E      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1723)
 E      at android.app.Activity.startActivityForResult(Activity.java:5314)
 E      at com.android.launcher3.Launcher.startActivityForResult(Unknown Source:5)
 E      at com.android.launcher3.BaseQuickstepLauncher.startActivityForResult(Unknown Source:22)
 E      at android.app.Activity.startActivity(Activity.java:5654)
 E      at com.android.launcher3.BaseDraggingActivity.startActivitySafely(Unknown Source:128)
 E      at com.android.launcher3.Launcher.startActivitySafely(:2)
 E      at com.android.launcher3.uioverrides.QuickstepLauncher.startActivitySafely(Unknown Source:8)
 E      at com.android.launcher3.touch.ItemClickHandler.startAppShortcutOrInfoActivity(:2)
 E      at f4.f.onClick(:20)
 E      at android.view.View.performClick(View.java:7448)
 E      at android.view.View.performClickInternal(View.java:7425)
 E      at android.view.View.access$3600(View.java:810)
 E      at android.view.View$PerformClick.run(View.java:28305)
 E      at android.os.Handler.handleCallback(Handler.java:938)
 E      at android.os.Handler.dispatchMessage(Handler.java:99)
 E      at android.os.Looper.loop(Looper.java:223)
 E      at android.app.ActivityThread.main(ActivityThread.java:7664)
 E      at java.lang.reflect.Method.invoke(Native Method)
 E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 E  Caused by: android.os.RemoteException: Remote stack trace:
 E      at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1043)
 E      at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:999)
 E      at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:669)
 E      at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1105)
 E      at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1077)
```
Additionally this also seems to be an issue in the old Lawnchair-V1. (Just let me know in case you also need a log for that)

**Comment by mbuett** [comment] 2021-07-04 21:38
This indeed is unrelated to Lawnchair. The problem also exists for the default LOS launcher (Trebuchet).

Came across the [related issue for SlimSocial](https://github.com/rignaneseleo/SlimSocial-for-Facebook/issues/136) and tried the changes from the [associated PR](https://github.com/rignaneseleo/SlimSocial-for-Facebook/pull/138). The problem does not occur anymore. 
So this actually has to be fixed by the authors of the apps that fail to launch.

**Comment by SphericalKat** [comment] 2021-07-05 12:13
Closing since it seems to be unrelated to lawnchair.

**Closed as completed by SphericalKat** 2021-07-05 12:13 UTC
