### ISSUE TITLE
Change Icons on a per app basis 

### ISSUE THREAD

**Issue by gautamhans1** [Deletescape-Media/Lawnchair#26] opened 2017-06-15 18:09 UTC
The user should be able to change the icon / iconpack used seperately for each app.
Clicking the icon in the app edit dialog would open a dialog which allows the selection of an icon pack and searching for an icon in the currently selected pack.

**Comment by deletescape** [comment] 2017-06-15 18:29
Actually... fy 🖕 

Duplicate of #6, closing this farken carnt shit bae

**Closed by deletescape** 2017-06-15 18:29 UTC
