### ISSUE TITLE
Dark theme in widget drawer

### ISSUE THREAD

**Issue by shuli81** [Deletescape-Media/Lawnchair#250] opened 2017-07-19 13:29 UTC
Currently dark theme does not apply in main widget drawer and app specific widget drawer.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment] 2017-07-19 14:52
Duplicate of #223

**Closed as completed** 2017-07-19 16:38 UTC
