### ISSUE TITLE
Launcher has no app suggestion bar

### ISSUE THREAD

**Issue by AndersonARS** [Deletescape-Media/Lawnchair#697] opened 2017-09-10 01:11 UTC
Do you have any possibility of it ?! All that's missing is for her to be perfect.

**Comment by LinuxLlama** [comment] 2017-09-10 01:35
Currently it's not added since it's buggy.

**Comment by suphon-t** [comment] 2017-09-10 07:20
Duplicate of many issues here and does not follow the issue template.

**Closed as completed by suphon-t** 2017-09-10 07:20 UTC
