### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by ildar** [Deletescape-Media/Lawnchair#676] opened 2017-09-05 08:41 UTC
It seems that the current v. 1.0.1063 has [troubles building in some environment](https://gitlab.com/fdroid/rfp/issues/319) while GIT HEAD is fine.
Could you please make a bugfix minor release? That'll help pushing Lawnchair to F-Droid.
Thanks in advance!

**Comment by jacksonhvisuals** [comment] 2017-09-06 01:20
Please note that you aren't allowed to push to F-Droid without our permission.

**Comment by ildar** [comment] 2017-09-06 02:38
Yes, precisely. I'm waiting in another issue.
Take your time to decide.

**Comment by ShadowRedel** [comment] 2017-09-06 11:28
@ildar you have here the new releases: https://lawnchairmirror.duckdns.org

**Comment by ildar** [comment] 2017-09-06 13:33
Ahh, nightly! No, I was meaning a Release, i.e. tagged commit in git.

**Comment by ShadowRedel** [comment] 2017-09-06 15:47
Ahh okay, sorry about that

**Comment by fonix232** [comment] 2017-10-10 10:50
Duplicate of #240

**Closed as completed by fonix232** 2017-10-10 10:50 UTC
