### ISSUE TITLE
Home Screen Shortcut not working (Google Weather)

### ISSUE THREAD

**Issue by anopows** [Deletescape-Media/Lawnchair#1253] opened 2018-06-09 14:34 UTC
## Description

In the Google App adding the weather shortcut is not working.

## Expected Behavior

A shortcut should appear on the home screen.

## Actual Behavior

None is visible afterwards.

## Steps to Reproduce

1. Open Google App
2. Open Weather section
3. Open settings (three dots)
4. Click: Add a Home screen shortcut

## Environment

* Device: OnePlus 3
* Android version: 8.0.0
* Launcher version: 1.1.0.1872
* Rom: Oxygen OS

## Logcat

```
your log here
```

**Comment by divadsn** [comment] 2018-06-09 14:36
@anopows Duplicate of x issues, please use search.

**Closed as completed** 2018-06-09 14:37 UTC
