### ISSUE TITLE
Notification Badges broken in dock

### ISSUE THREAD

**Issue by fishears** [Deletescape-Media/Lawnchair#49] opened 2017-06-27 14:07 UTC
Running the 198 release on 8.0 (preview 3) I don't see notification dots on any app icons or notification previews. Tried with pixel icons on and off. Am I missing something obvious?
App shortcuts and widget bottom bar work perfectly.

**Comment by deletescape** [comment] 2017-06-27 14:43
Have you granted Notification Access to Lawnchair?

**Comment by hitokiri8x** [comment] 2017-06-27 15:23
I can confirm that notifications does work ( maybe you need to give permission) 
What is bugged or design intented, I don't know, is that notification badge is not shown on the docked ( bottom) icon.
You can try docking and undocking an app with a notification.
Preview works fine

**Comment by fishears** [comment] 2017-06-27 15:39
derp. Forgot about notification access - I always think that will be in permissions if needed but of course it's not... Working now - except in the dock which is where it would be most useful for me :(

**Comment by deletescape** [comment] 2017-06-27 15:41
Yeah, seems to be broken in the dock, should be fixed by next week

**Comment by fishears** [comment] 2017-06-27 15:42
you are a hero. Where can we donate to you for your hard work?

**Comment by deletescape** [comment] 2017-06-27 15:47
Thanks a lot :blush:
[Pay Pal Donation Link](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=E2EFKTUC62KDQ)

**Comment by fishears** [comment] 2017-06-27 16:07
Done. 
1XE79251DC3231535

**Comment by TokedUp** [comment] 2017-06-27 17:00
My notification dots work on Gmail when in the dock. But the app is in a folder. Messenger dots don't work anywhere not matter in dock or not. 

77301949YX592971E couple beers for u sir. Please keep up the great work. Maybe we can get that weather widget soon 😉

**Comment by tstackhouse** [comment] 2017-06-27 19:45
Probably not the place for this, but 5JB48930UL495303X.  Thanks for this, and don't let people trying to browbeat you into making features for them get to ya.  This is a labour of love 💘.

**Comment by dhrandy** [comment] 2017-06-27 21:37
On my S8 I haven't seen any notifications. I do have notifications allowed.

**Closed** 2017-07-10 15:26 UTC
Labels: bug
