### ISSUE TITLE
Lawnchair request 29

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#84] opened 2017-06-28 14:19 UTC
In case I didn't mention it earlier, please put notification access in Launcher settings. There, it will be easier to enable notification badges

**Comment by deletescape** [comment] 2017-06-28 19:36
Duplicate of #64

**Closed by deletescape** 2017-06-28 19:36 UTC
Labels: duplicate

**Comment by fonix232** [comment] 2017-06-29 20:25
@Dondrejohnson5 please use talking names for the request titles! Numbering them makes it hard to track (for pure reference we have the actual issue number, e.g. this is issue #84), and is also quite annoying.

And please make use of the search feature. If you continue to duplicate existing issues, you will be restricted from posting further issue reports. This is your first, last and final warning.
