### ISSUE TITLE
Lawnchair request 10

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#61] opened 2017-06-27 19:08 UTC
Ability to edit app icon to Traditional, Pixel, icon pack, or custom from gallery apps, like Google Drive or Google Photos

**Comment by deletescape** [comment] 2017-06-27 20:34
Closing this for now, might reconsider this in the future (also, partial duplicate of #25 )

**Closed by deletescape** 2017-06-27 20:34 UTC
