### ISSUE TITLE
Crash when opening/tapping most widgets (v12 alphas 1 & 2)

### ISSUE THREAD

**Issue by cooperka** [Deletescape-Media/Lawnchair#2264] opened 2021-10-25 16:58 UTC
I installed the recent v12-a1 release after upgrading to android 12 yesterday (Pixel 4a5g), starting from scratch with a fresh homescreen (no prior data because it was an old version of Lawnchair with a different app key).

Every widget I've tested so far crashes on the SECOND open/interaction (first interaction is fine). For example, Audible opened the app on first widget tap, then when I went back to homescreen and tapped again, Lawnchair crashed. It also crashes if I just press the "play" button on the widget.

I was unable to send/view stack trace, happy to reproduce again if helpful.

**Comment by vladrevers** [comment] 2021-10-25 21:37
v12 alpha 2 - Not fixed. Crash but with a different error:
Android 12, Pixel 4a
`E/AndroidRuntime(14244): Process: app.lawnchair, PID: 14244
java.lang.SecurityException: Permission Denial: registerRemoteAnimationForNextActivityStart from pid=14244, uid=10611 requires android.permission.CONTROL_REMOTE_APP_TRANSITION_ANIMATIONS
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IActivityTaskManager$Stub$Proxy.registerRemoteAnimationForNextActivityStart(IActivityTaskManager.java:4361)
	at com.android.launcher3.uioverrides.QuickstepInteractionHandler.onInteraction(Unknown Source:60)
	at android.appwidget.AppWidgetHostView.lambda$getHandler$1$AppWidgetHostView(AppWidgetHostView.java:874)
	at android.appwidget.AppWidgetHostView$$ExternalSyntheticLambda2.onInteraction(Unknown Source:4)
	at android.widget.RemoteViews$RemoteResponse.handleViewInteraction(RemoteViews.java:6439)
	at android.widget.RemoteViews$RemoteResponse.access$200(RemoteViews.java:6287)
	at android.widget.RemoteViews$SetOnClickResponse.lambda$apply$0$RemoteViews$SetOnClickResponse(RemoteViews.java:1140)
	at android.widget.RemoteViews$SetOnClickResponse$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7441)
	at android.view.View.performClickInternal(View.java:7418)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28676)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforceCallingPermission(ActivityManagerService.java:5453)
	at com.android.server.am.ActivityManagerService$LocalService.enforceCallingPermission(ActivityManagerService.java:15580)
	at com.android.server.wm.ActivityTaskManagerService.registerRemoteAnimationForNextActivityStart(ActivityTaskManagerService.java:3560)
	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:2052)
	at com.android.server.wm.ActivityTaskManagerService.onTransact(ActivityTaskManagerService.java:5013)
`

**Comment by cooperka** [comment] 2021-10-25 21:51
I can also confirm @vladrevers that alpha 2 does NOT resolve this issue, even though it claims to in the release notes.

**Comment by suphon-t** [comment] 2021-10-26 01:54
Fixed in 8e10f39.

**Closed as completed by suphon-t** 2021-10-26 01:54 UTC
