### ISSUE TITLE
Transparent Dock

### ISSUE THREAD

**Issue by mrcadillac** [Deletescape-Media/Lawnchair#551] opened 2017-08-18 19:49 UTC
When I toggle transparent dock the arrow above the dock goes below it.

**Comment by intelligentcasanova** [comment] 2017-08-18 21:45
This is the intended behaviour. See #223. Please close this issue.

**Comment by ghost** [comment] 2017-08-18 22:57
Can you add an option to have it ontop?

**Comment by nyancrimew** [comment] 2017-08-19 06:59
No

**Closed as completed by nyancrimew** 2017-08-19 06:59 UTC
