### ISSUE TITLE
Crashing when using Lawnchair+QuickSwitch for recents with gestures.

### ISSUE THREAD

**Issue by ashabraja2** [Deletescape-Media/Lawnchair#2085] opened 2021-02-24 01:45 UTC
Lawnchair crashes when using navigation gestures from an app. Swipe gestures only activate QuickSwitch when on the homescreen itself. Anywhere else and it crashes.

The recents work completely fine when you are using a normal 3-button navigation bar or a remapped physical key. The issue only arises when using gestures.

I should add that my device is a Galaxy S8 950F on a (OneUI) Android 10 port ROM, though I'm not sure that's the root of the issue. The gestures worked with Lawnchair perfectly fine on Android 9 with this skin however.

```
Lawnchair bug report 24 Feb 2021 01:39:04
Lawnchair version: 10.0 Alpha 8 (10002926)
build.brand: samsung
build.device: crownlte
build.display: hadesRom_Q_OneUI_v1.0-FTK3
build.fingerprint: samsung/crownltexx/crownlte:10/QP1A.190711.020/N960FXXS6FTK3:user/release-keys
build.hardware: samsungexynos8895
build.id: QP1A.190711.020
build.manufacturer: samsung
build.model: SM-G965F
build.product: crownltexx
build.type: user
version.codename: REL
version.incremental: N960FXXS6FTK3
version.release: 10
version.sdk_int: 29
display.density_dpi: 450

error: Uncaught exception

--------- beginning of stacktrace
java.lang.AbstractMethodError: abstract method "void android.view.IRecentsAnimationRunner.reportAllDrawn()"
	at android.view.IRecentsAnimationRunner$Stub.onTransact(IRecentsAnimationRunner.java:152)
	at android.os.Binder.execTransactInternal(Binder.java:1056)
	at android.os.Binder.execTransact(Binder.java:1029)

```

**Comment by DanGLVK** [comment] 2021-02-24 02:36
@ashabraja2 The issue is known on One UI 2.5, they've slightly changed their Quickstep implementation (so most/all Quickstep compatible launchers don't work correctly)

It seems they've undid such changes on One UI 3, but unfortunately Lawnchair 11 isn't ready for release just yet

Most i can tell you at the moment is to wait patiently until a solution for this issue can be found

**Comment by RikKoedoot** [comment] 2021-08-27 11:10
Closing because effort has been moved to v11

**Closed as completed by RikKoedoot** 2021-08-27 11:10 UTC
