### ISSUE TITLE
Launcher Shortcuts and Icon Customization

### ISSUE THREAD

**Issue by silentgurdian** [Deletescape-Media/Lawnchair#415] opened 2017-08-06 08:23 UTC
It would be great if launcher shortcuts could be backported to Android 5.1 and if the shortcut box didn't cut off at the screen edge for apps in the middle. And if icons could be selected from pngs in gallery that would be quite helpful as well.

**Comment by suphon-t** [comment] 2017-08-07 03:05
Duplicate of #233

**Closed as completed by suphon-t** 2017-08-07 03:05 UTC
