### ISSUE TITLE
Little "bar" showing comping off the corner of the shortcuts menu

### ISSUE THREAD

**Issue by brody192** [Deletescape-Media/Lawnchair#527] opened 2017-08-14 17:41 UTC
https://imgur.com/oGhZUZN

LG g5 
Stock 7.0
Lowest display setting

**Comment by intelligentcasanova** [comment] 2017-08-14 18:34
Duplicate of #78.
Please search existing issues before opening a new one.

**Closed as completed** 2017-08-14 18:38 UTC
