### ISSUE TITLE
[FEATURE REQUEST] Option to change folder icons

### ISSUE THREAD

**Issue by shuli81** [Deletescape-Media/Lawnchair#447] opened 2017-08-08 15:23 UTC
Ability to use custom icons for folders instead of the default preview icon.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment] 2017-08-08 15:54
Duplicate of #291

**Closed as completed** 2017-08-08 18:04 UTC
