### ISSUE TITLE
Duplicate Apps When Adding Apps To Folder

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [Deletescape-Media/Lawnchair#4780] opened 2024-09-08 11:49 UTC
### Describe the bug

When I add apps directly to a folder on the home screen or dock from the drawer, it often times duplicates the app on the homescreen, resulting in the app being both on the homescreen and in the folder. I can easily remove it. Sometimes if I do this several times, the duplicate apps will overlap.

### Steps to reproduce

1. Go to app drawer
2. Drag an app to a folder on the homescreen or dock
3. See duplicate app at the top

May need to try folders in different positions. 

### Expected behavior

I should be able to add apps directly to a folder on the home screen or dock from the drawer without duplicates being created on the homescreen.

### Device information

- Device: Google Pixel 6a
- OS: Android version 14
- App version: 14.Beta 3

**Comment by tgex0** [comment] 2024-09-08 13:18
Duplicate of #4446

**Closed as completed** 2024-12-14 19:41 UTC
Labels: bug
