### ISSUE TITLE
Graphic glitch in app-shortcuts

### ISSUE THREAD

**Issue by samshiver** [Deletescape-Media/Lawnchair#540] opened 2017-08-17 08:14 UTC
Hey, I've noticed that when I use the smallest DPI setting (I'm running 7.1.2 Nougat on a Nexus 5X) the app-shortcuts have a weird white mark on the top-right corner which doesn't appear on the default DPI setting (see SCREENSHOT1). 
![screenshot1](https://user-images.githubusercontent.com/31093306/29402236-8fa7f1b8-8334-11e7-8bb4-9aaf71fff8be.png)

Moreover, if I use 4 columns (homescreen and/or app drawer), the app-shortcuts of the third icons (starting from the left) won't display properly: they can't fit the screen (I think they should be showed on the left of the icon, not on the right; see SCREENSHOT2).
![screenshot2](https://user-images.githubusercontent.com/31093306/29402266-a0f3ae9e-8334-11e7-8a2c-090527efc02e.png)

I also want to add that sometimes the closing animation of the app-shortcuts acts weird. There's some kind of graphic glitch: while fading out, the app-shortcut seems to appear for a moment in another place next to the icon... it happens randomly (unfortunately I can't show you)

Thank you for your attention

**Comment by intelligentcasanova** [comment] 2017-08-17 09:34
Duplicate of #228.

**Comment by intelligentcasanova** [comment] 2017-08-17 09:34
Duplicate of #78.

**Comment by intelligentcasanova** [comment] 2017-08-17 09:36
Duplicate of #212.

**Closed as completed** 2017-08-17 09:51 UTC
