### ISSUE TITLE
[Surface Duo] InstaCrash

### ISSUE THREAD

**Issue by Hammerfest** [Deletescape-Media/Lawnchair#2181] opened 2021-07-04 03:31 UTC
Latest Alpha, haven't tested older ones.
I saw a few posts on XDA and Reddit talking about it working fine (probably earlier Alpha), but I got crash galore (wont even work -at-all- ).

Will try to get logs to append tomorrow.

**Comment by AshH2O** [comment] 2021-07-13 07:58
Same happens on my Samsung Galaxy A32 4G edition

**Comment by RikKoedoot** [comment] 2021-07-13 10:13
If you're on a Samsung, do this: Disable gesture navigation, open Lawnchair, enable gesture navigation again.

**Comment by RikKoedoot** [comment] 2021-08-26 21:26
Does this crash still occur? (On the surface duo)

**Comment by Hammerfest** [comment] 2021-08-26 21:30
Yes, just tested latest Alpha version, attempting to open instacrash's 
I have not tried a recommend workaround I saw which was disabling the Microsoft launcher through adb, dont wanna be without launcher if it fails to work even with microsoft launcher disabled.

**Comment by RikKoedoot** [comment] 2021-08-26 21:37
Could you provide a crash log? 

For Lawnchair V11:
1. Download and install the Scoop app: https://github.com/TacoTheDank/Scoop
2. Grant permissions to the app using either root or via adb using the command adb shell pm grant taco.scoop android.permission.READ_LOGS
3. Reproduce the crash
4. Upload the stacktrace to catbin
5. Paste link of the crash log in the chat

**Comment by SuperDragonXD** [comment] 2022-08-04 06:31
Very late reply, but since you're in Lawnchair 11, try updating to the later versions (Lawnchair 12.1) and see if it fixes the issue. Also closing since this is relevant to the older versions only (we no longer support older versions).

**Closed as completed by SuperDragonXD** 2022-08-04 06:31 UTC
Labels: bug
