### ISSUE TITLE
Wrong colors in status bar

### ISSUE THREAD

**Issue by bepaald** [Deletescape-Media/Lawnchair#1515] opened 2019-04-19 13:10 UTC
When the status bar changes from a dark color to a light one, the text and icon in the bar should probably turn dark. However, the behavior I see is that only the time and battery icon change color, while the rest stays light (and nearly invisible).

![issue1](https://user-images.githubusercontent.com/38437099/56425315-3df26d80-62a3-11e9-948a-4a48157f45ec.gif)

When the app drawer is shown, the same thing happens. However in this case, even though the app drawer background is white, I think because of the low opacity (set at 20%) of the background, the status bar icons shouldn't even change color at all. The icons that fail to change color are much more visible than the ones that do:

![2019_04_18_22_14_40-0150](https://user-images.githubusercontent.com/38437099/56425387-9a558d00-62a3-11e9-918f-087fa1c411d9.jpg)

I also think the icon labels are not very readable in this view, they should probably be white as well.

I tried changing the theme from 'light' to 'light with dark text', but there don't seem to be any visible differences as far as I can tell.

Thanks!

Device: ZTE Zmax Pro (Z981)
Android version: 6.0.1
Launcher version: 2.0-1995-ci-alpha

**Comment by bohrabhijeet** [comment] 2019-04-19 13:14
@bepaald That is a known issue on Marshmallow and has been fixed in internal builds.

**Comment by RikKoedoot** [comment] 2019-04-22 09:53
the statusbar may be your device not fully supporting the different colors,
about the labels, they are dark, as on a light theme light text would be even less readable.

**Comment by suphon-t** [comment] 2019-04-22 10:00
Closing as it’s caused by the device itself.

**Closed as completed by suphon-t** 2019-04-22 10:00 UTC
