### ISSUE TITLE
Lag when opening and closing folders

### ISSUE THREAD

**Issue by Jordan-Glass** [Deletescape-Media/Lawnchair#1994] opened 2020-05-11 21:52 UTC
## Description

When icon shape in launcher settings is set to Square, rounded square, squircle, teardrop or cylinder the animation when opening and closing folders is laggy. Circle and set by system are fine.

In developer options my animations are all set to 0.5x. Setting them to 1x makes the problem less apparent but it is still there.

It seems to be related to how many folders are on one page. Moving my folders from one page to another, one by one, it was as it should be at first but as I added more it became laggier. Disabling Blur has no effect.

Folders in cover mode might not count towards this "cap" but are affected by it.

![Screenshot_20200511-224928_Lawnchair](https://user-images.githubusercontent.com/18504622/81615554-b4479d80-93d9-11ea-9396-8e6989961664.jpg)

Circled folder has smooth animations on it's own page but not as it is in this screenshot. Have tested with other folders and they are affected too, it's not just this set of apps.

## Expected Behavior

Animations run at a smooth frame rate.

## Actual Behavior

The animations are laggy, both in the sense that there are a lot of dropped frames and the animation takes longer than it should to complete.

## Steps to Reproduce

1. Create several folders on a single page and one on another page
2. Make sure icon shape is set to rounded square etc
3. Animation of the single folder is as it should be, move it to the page with the other folders and it is not
4. Change icon shape to set by system or circle and check the difference

## Environment

* Device: Samsung Galaxy A70 A705FN
* Android version: 10 / February 2020
* Launcher version: 2.0-2589
* Rom: stock OneUI 2.0

I do not have an icon pack enabled

**Comment by DanGLVK** [comment] 2020-05-11 22:09
> ## Description
> When icon shape in launcher settings is set to Square, rounded square, squircle, teardrop or cylinder the animation when opening and closing folders is laggy. Circle and set by system are fine.
> 
> In developer options my animations are all set to 0.5x. Setting them to 1x makes the problem less apparent but it is still there.
> 
> It seems to be related to how many folders are on one page. Moving my folders from one page to another, one by one, it was as it should be at first but as I added more it became laggier. Disabling Blur has no effect.
> 
> Folders in cover mode might not count towards this "cap" but are affected by it.
> 
> ![Screenshot_20200511-224928_Lawnchair](https://user-images.githubusercontent.com/18504622/81615554-b4479d80-93d9-11ea-9396-8e6989961664.jpg)
> 
> Circled folder has smooth animations on it's own page but not as it is in this screenshot. Have tested with other folders and they are affected too, it's not just this set of apps.
> 
> ## Expected Behavior
> Animations run at a smooth frame rate.
> 
> ## Actual Behavior
> The animations are laggy, both in the sense that there are a lot of dropped frames and the animation takes longer than it should to complete.
> 
> ## Steps to Reproduce
> 1. Create several folders on a single page and one on another page
> 2. Make sure icon shape is set to rounded square etc
> 3. Animation of the single folder is as it should be, move it to the page with the other folders and it is not
> 4. Change icon shape to set by system or circle and check the difference
> 
> ## Environment
> * Device: Samsung Galaxy A70 A705FN
> * Android version: 10 / February 2020
> * Launcher version: 2.0-2589
> * Rom: stock OneUI 2.0
> 
> I do not have an icon pack enabled

the issue is caused by the folders having an adaptive shape, and due to how Android renders them a lot of non-circle folders will cause significant overhead on the device, we have been looking into ways to workaround/fix this as best as we can but the heart of the issue lies with how Android renders adaptive folders, the folder isn't a simple icon but rather a somewhat complex vector drawable (it's done this way so they can be adaptive) and non-circle shapes simply makes the Android renderer struggle when it has to draw too many of them

**Comment by Jordan-Glass** [comment] 2020-05-11 22:27
> > ## Description
> > When icon shape in launcher settings is set to Square, rounded square, squircle, teardrop or cylinder the animation when opening and closing folders is laggy. Circle and set by system are fine.
> > In developer options my animations are all set to 0.5x. Setting them to 1x makes the problem less apparent but it is still there.
> > It seems to be related to how many folders are on one page. Moving my folders from one page to another, one by one, it was as it should be at first but as I added more it became laggier. Disabling Blur has no effect.
> > Folders in cover mode might not count towards this "cap" but are affected by it.
> > ![Screenshot_20200511-224928_Lawnchair](https://user-images.githubusercontent.com/18504622/81615554-b4479d80-93d9-11ea-9396-8e6989961664.jpg)
> > Circled folder has smooth animations on it's own page but not as it is in this screenshot. Have tested with other folders and they are affected too, it's not just this set of apps.
> > ## Expected Behavior
> > Animations run at a smooth frame rate.
> > ## Actual Behavior
> > The animations are laggy, both in the sense that there are a lot of dropped frames and the animation takes longer than it should to complete.
> > ## Steps to Reproduce
> > 
> > 1. Create several folders on a single page and one on another page
> > 2. Make sure icon shape is set to rounded square etc
> > 3. Animation of the single folder is as it should be, move it to the page with the other folders and it is not
> > 4. Change icon shape to set by system or circle and check the difference
> > 
> > ## Environment
> > 
> > * Device: Samsung Galaxy A70 A705FN
> > * Android version: 10 / February 2020
> > * Launcher version: 2.0-2589
> > * Rom: stock OneUI 2.0
> > 
> > I do not have an icon pack enabled
> 
> the issue is caused by the folders having an adaptive shape, and due to how Android renders them a lot of non-circle folders will cause significant overhead on the device, we have been looking into ways to workaround/fix this as best as we can but the heart of the issue lies with how Android renders adaptive folders, the folder isn't a simple icon but rather a somewhat complex vector drawable (it's done this way so they can be adaptive) and non-circle shapes simply makes the Android renderer struggle when it has to draw too many of them

Makes sense, thanks for taking a look.

**Comment by DanGLVK** [comment] 2020-05-11 22:30
> > > ## Description
> > > When icon shape in launcher settings is set to Square, rounded square, squircle, teardrop or cylinder the animation when opening and closing folders is laggy. Circle and set by system are fine.
> > > In developer options my animations are all set to 0.5x. Setting them to 1x makes the problem less apparent but it is still there.
> > > It seems to be related to how many folders are on one page. Moving my folders from one page to another, one by one, it was as it should be at first but as I added more it became laggier. Disabling Blur has no effect.
> > > Folders in cover mode might not count towards this "cap" but are affected by it.
> > > ![Screenshot_20200511-224928_Lawnchair](https://user-images.githubusercontent.com/18504622/81615554-b4479d80-93d9-11ea-9396-8e6989961664.jpg)
> > > Circled folder has smooth animations on it's own page but not as it is in this screenshot. Have tested with other folders and they are affected too, it's not just this set of apps.
> > > ## Expected Behavior
> > > Animations run at a smooth frame rate.
> > > ## Actual Behavior
> > > The animations are laggy, both in the sense that there are a lot of dropped frames and the animation takes longer than it should to complete.
> > > ## Steps to Reproduce
> > > 
> > > 1. Create several folders on a single page and one on another page
> > > 2. Make sure icon shape is set to rounded square etc
> > > 3. Animation of the single folder is as it should be, move it to the page with the other folders and it is not
> > > 4. Change icon shape to set by system or circle and check the difference
> > > 
> > > ## Environment
> > > 
> > > * Device: Samsung Galaxy A70 A705FN
> > > * Android version: 10 / February 2020
> > > * Launcher version: 2.0-2589
> > > * Rom: stock OneUI 2.0
> > > 
> > > I do not have an icon pack enabled
> > 
> > 
> > the issue is caused by the folders having an adaptive shape, and due to how Android renders them a lot of non-circle folders will cause significant overhead on the device, we have been looking into ways to workaround/fix this as best as we can but the heart of the issue lies with how Android renders adaptive folders, the folder isn't a simple icon but rather a somewhat complex vector drawable (it's done this way so they can be adaptive) and non-circle shapes simply makes the Android renderer struggle when it has to draw too many of them
> 
> Makes sense, thanks for taking a look.

You're welcome, if we find a way to workaround this we'll be sure to notify you

**Comment by RikKoedoot** [comment] 2021-08-27 11:29
Closing because effort has been moved to v11

**Closed as completed by RikKoedoot** 2021-08-27 11:29 UTC
