### ISSUE TITLE
[Feature Request] Search box for custom icon selection

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#794] opened 2017-10-02 09:24 UTC
Please consider adding a search box in icon selection window. Thanks.

Screenshot https://imgur.com/a/ysXDH

**Comment by pjtsearch** [comment] 2017-10-07 16:40
I agree

**Comment by fonix232** [comment] 2017-10-12 13:48
Duplicate of #665

**Closed as completed by fonix232** 2017-10-12 13:48 UTC
