### ISSUE TITLE
Feature request: suggested apps in drawer

### ISSUE THREAD

**Issue by theandroidenthusiast** [Deletescape-Media/Lawnchair#711] opened 2017-09-12 10:19 UTC
Hey there, can you please implement app suggestions like in the stock Pixel launcher? And can you also change the font color of the search bar into the drawer to accent color as for the black theme you can barely read the font due it being grey. Thank you

**Comment by divadsn** [comment] 2017-09-12 10:23
Duplicate of many issues, **please read the issue template!**

**Closed as completed by divadsn** 2017-09-12 10:23 UTC
