### ISSUE TITLE
Icon shape support for all apps

### ISSUE THREAD

**Issue by bappa555** [Deletescape-Media/Lawnchair#2853] opened 2022-08-20 04:57 UTC
### Describe the feature

Please support icon shape for all apps like it use to work on Lawnchair 2
For example few oxygen OS 12 stock apps (e.g. - contacts, files, photo) does to adhire icon shape defined in Lawnchair 12. But in previous version Lawnchair 2, all apps ( including 3rd party apps) use to get the icon shape applied. 

![Screenshot_2022-08-20-10-25-51-75_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/29393112/185729580-ab08bc76-b567-4198-bd45-7f92c2ae46b9.png)

### Why would it be useful to add?

If this is implemented, then all the icons will looks same with defined shape.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

Please refer the screenshot

**Comment by Amorphous404** [comment] 2022-08-20 09:34
This feature to force reshape legacy icons exists already.

Got to Lawnchair Settings>General>Toggle On Auto Adaptive Icons.

**Comment by kahanzammi** [comment] 2022-08-20 10:09
This feature exists, but behavior is not same as V2 - where in V2, force to shape legacy icons used to fill the shape. But in V12, it minimizes the icon into the selected shape.

Example: Take a look at 'Petal Maps' icon below.

**Comment by kahanzammi** [comment] 2022-08-20 10:20
![Screenshot_20220820-141534_Lawnchair~2](https://user-images.githubusercontent.com/105884763/185741585-123b9048-2ac3-4765-874e-c520caf71a65.png)

**Comment by Amorphous404** [comment] 2022-08-20 12:32
> This feature exists, but behavior is not same as V2 - where in V2, force to shape legacy icons used to fill the shape. But in V12, it minimizes the icon into the selected shape.
> 
> Example: Take a look at 'Petal Maps' icon below.

Yes, ik, the user asked about how to reshape, so i pointed out the option to enable it, forcing the reshape legacy icons is almost same ig it just for some squarish icons it doesn't force reshape with a background and just crops the icon to be Adaptive but

All in all that's a different feature request 😅

**Comment by kahanzammi** [comment] 2022-08-20 13:36
It's all about out of the box user experience. 
This is how Petal Maps' icon in V2 without user messing around with the settings. 

![Screenshot_20220820-172525_Lawnchair~2](https://user-images.githubusercontent.com/105884763/185748537-36a9ce7b-8fa9-49d1-8107-72cf607d0a9f.png)

**Comment by Amorphous404** [comment] 2022-08-20 16:23
> It's all about out of the box user experience. 
> This is how Petal Maps' icon in V2 without user messing around with the settings. 
> 
> ![Screenshot_20220820-172525_Lawnchair~2](https://user-images.githubusercontent.com/105884763/185748537-36a9ce7b-8fa9-49d1-8107-72cf607d0a9f.png)
> 

That's because it's not an adaptive icon, and i was suggesting the user that opened the ticket to enable adaptive icon to have consistent shape across all icons

And what you're requesting is to bring back the old reshape legacy icons style from v2 that has already been requested #2737

**Comment by yasanglass** [comment] 2022-08-21 05:08
Duplicate of #2737.

**Closed as completed by yasanglass** 2022-08-21 05:08 UTC
Labels: enhancement, feature-request
