### ISSUE TITLE
Navigation button color correction

### ISSUE THREAD

**Issue by akapu1** [Deletescape-Media/Lawnchair#278] opened 2017-07-22 05:21 UTC
Hi.. I am using this awesome launcher in my Galaxy S8.. but due to Samsung's fault all 3rd party launcher except Nova shows muted color of Navigation button: gray instead of white. Nova launcher has corrected this problem somehow. Could you please take a look into this matter so that navigation button color shows white instead of gray in home screen..? You can check my screen shot.
Thank you..! 

![](http://i.imgur.com/RTssGhp.jpg)

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suphon-t** [comment] 2017-07-22 06:13
Duplicate of #120

**Closed as completed by suphon-t** 2017-07-22 06:13 UTC
