### ISSUE TITLE
[Bug] Jittery Slide Animation Upon Returning From Google Now Page

### ISSUE THREAD

**Issue by tschlunk** [Deletescape-Media/Lawnchair#965] opened 2017-11-22 22:25 UTC
## Description

A strange animation plays when returning home from a Google search or Google Now card.

## Expected Behavior

When pressing the home button, I should go back to the home page with a normal 'reveal' animation.

## Actual Behavior

A jittery side-to-side animation (presumably a messed up slide animation) plays when returning home from a Google search or Google Now card accessed via Lawnfeed.

## Steps to Reproduce

1. Enable Google Now page.
2. Swipe to the Google Now page and make a search or tap any card. **Do not** press the x or back button to return to the main Google Now page.
3. Press the home button to return home.
4. Observe the jittery animation.

I can upload a video if you have difficulty reproducing the bug.

## Environment

* Device: ONEPLUS A3000
* Android version: 7.1.1
* Launcher version: 1.1.0.1594
* Lawnfeed version: 1.1.0.1583
* Rom: Stock OxygenOS 4.5.1

**Comment by divadsn** [comment] 2017-11-22 22:28
Duplicate of #869

**Comment by tschlunk** [comment] 2017-11-22 22:29
Sorry I looked but didn't see that one

**Closed as completed** 2017-11-22 22:29 UTC
