### ISSUE TITLE
OnePlus Clock app not recognized by the Lawnchair At A Glance widget

### ISSUE THREAD

**Issue by The-Fireplace** [Deletescape-Media/Lawnchair#1909] opened 2020-01-17 16:38 UTC
## Description
The at a glance widget on the Lawnchair home screen does not detect my phone's clock app when I click it, and says "App not installed."

## Expected Behavior
The clock app opens when I click the time on the Lawnchair at a glance widget

## Actual Behavior
"App not installed." Shows up when I click the time on the Lawnchair at a glance widget.

## Steps to Reproduce
1. Have Lawnchair on a OnePlus device (I tested on a OnePlus 7 Pro 5G)
2. Tap the time on the Lawnchair "At a glance" widget.

## Environment

* Device: OnePlus 7 Pro 5G
* Android version: 9
* Launcher version: 2.0-2589

**Comment by kursmappe** [comment] 2020-01-20 10:41
Same behavior/issue on my Samsung Galaxy S9, which is also running Android 9 and Lawnchair 2.0-2589.

**Comment by LuminarySage** [comment] 2020-01-22 20:23
I have asked the devs about this issue before. It has something to do with OnePlus' clock app altering its alarm intent so it can't be called directly or something along that line.

**Comment by LuminarySage** [comment] 2020-01-22 20:26
Also most likely a duplicate of #1559

**Comment by JimPix1** [comment] 2022-02-12 22:21
I'm also having this issue on my Samsung Galaxy A22

**Comment by JimPix1** [comment] 2022-02-12 22:27
I'm also having this issue on my Samsung Galaxy A22

**Comment by SuperDragonXD** [comment] 2022-08-04 06:27
Very late, but closing this issue due to it being a OnePlus issue (OnePlus' clock app altering its alarm intent so it can't be called directly) and not a Lawnchair issue.

**Closed as completed by SuperDragonXD** 2022-08-04 06:27 UTC
