### ISSUE TITLE
Weather is not showing up on right top corner of the home screen

### ISSUE THREAD

**Issue by johndoe422** [Deletescape-Media/Lawnchair#254] opened 2017-07-20 06:05 UTC
I am using this launcher in my Redmi Note3 running Resurrection Remix Rom (Nougat 7.1.2)  16-Jul-17 build. The launcher shows the day & date on the top right portion of the screen, whereas Pixel launcher shows the weather in that area.

**Comment by maximemhd** [comment] 2017-07-20 07:14
#21

**Comment by mehmetcanbozkus** [comment] 2017-07-20 07:39
Best Launcher

**Comment by suphon-t** [comment] 2017-07-20 08:33
Duplicate of #21

**Closed as completed by suphon-t** 2017-07-20 08:33 UTC
