### ISSUE TITLE
Update to match the new PIxel Launcher

### ISSUE THREAD

**Issue by JacobDB** [Deletescape-Media/Lawnchair#808] opened 2017-10-05 21:57 UTC
WIth the Pixel 2 and Pixel 2 XL, the launcher is getting a refresh. [See screens in this hands-on article](https://www.theverge.com/2017/10/4/16405192/new-google-pixel-2-xl-phone-photos-video-hands-on). In general, the following changes appear to have been made:

- The "pill" has been removed
- Next upcoming calendar event is displayed above the date & weather
- The date & weather are centered at the top of the first page of the launcher
- A search bar is placed below the icons in the dock
- The search bar in the app drawer is now the same as the search bar in the dock; swiping up transitions the search bar to the top of the app drawer.

I'm thinking there will be some people who don't like some of these changes, so perhaps there could be options? I think the biggest descent will be around the search bar in the dock; a setting to disable this or display it at the top of the launcher may be a good idea.

![new-launcher-style](https://user-images.githubusercontent.com/1123997/31254559-c9a3f50c-a9ee-11e7-854e-85c3e6901331.png)

**Comment by LinuxLlama** [comment] 2017-10-05 23:38
I don't think it's possible right now because the new Pixel Launcher source isn't available yet.

**Comment by JacobDB** [comment] 2017-10-06 00:06
Yea, I wouldn't expect it to be done until it comes out.

**Comment by nyancrimew** [comment] 2017-10-06 04:50
Duplicate of #786

**Closed as completed by nyancrimew** 2017-10-06 04:50 UTC
