### ISSUE TITLE
Add feature to app drawer

### ISSUE THREAD

**Issue by Joni5664** [Deletescape-Media/Lawnchair#576] opened 2017-08-23 00:43 UTC
If after pulling down (on home screen) search bar opens and keyboards pops up to type, then after typing in the name or part of the name,  instead of SEARCH can that be replaced with ENTER/SELECT to open the app instead of searching the word you typed in the Play Store. Let me know if I'm not clear and I'll try again.

**Comment by faroit** [comment] 2018-08-08 18:26
i guess this is a dupe of #98 

I would really support this feature. Its also the default behavior for nova launcher. I don't think it makes sense that the enter/loupe key will get you to the play store by default. Simply launching the 1st ranked hit would make more sense.

There is still way to search the play store below the search results

**Comment by Joni5664** [comment] 2018-08-08 18:36
After they said it couldn't be done it works now, after a few updates. Check it out. Best launcher for me still.

**Comment by faroit** [comment] 2018-08-08 18:42
It doesn't work in v2 alpha :-/ ![image](https://user-images.githubusercontent.com/72940/43857434-95fdda2a-9b4b-11e8-99ac-ee35835dc519.png)

**Comment by faroit** [comment] 2018-08-08 18:45
Also its the same in v1 stable from the play store

![image](https://user-images.githubusercontent.com/72940/43857577-fba604ce-9b4b-11e8-8c5c-722334f04c44.png)


did you set some special settings (or do not use the gboard keyboard?)?

**Comment by faroit** [comment] 2018-08-10 10:43
looks like [this](https://github.com/LawnchairLauncher/Lawnchair/blob/7759136b41c7ddd85033f17ad93dc60ba44ac4e8/app/src/main/java/ch/deletescape/lawnchair/allapps/AllAppsSearchBarController.java#L118) is the code that sends the request to the play store. 

I would propose to optionally launch the 1st search result hit app. 

@deletescape, what do you think about this? I could make a PR.

**Comment by nyancrimew** [comment] 2018-08-10 10:47
@faroit I'm not sure if it is still Worth your time to implement it in V1 as our main focus in on V2, but as that part of the code is more or less still the same in V2 I could simply cherry pick it to there. So if you have enough time and feel like doing this, feel free to do so.

**Comment by faroit** [comment] 2018-08-10 11:01
@deletescape I'm fine with only implementing it for v2. Is v2 based on the alpha branch? Can you point me to the right folder, please?

**Comment by divadsn** [comment] 2018-08-10 11:01
@faroit v2 source isn't released yet.

**Comment by faroit** [comment] 2018-08-10 11:05
I see. I will wait then. I thought the alpha branch is v2. I would recommend to add a note on the main readme of this project.

**Closed as completed** 2019-04-07 11:58 UTC
