### ISSUE TITLE
[FEATURE] Widgets stack - save homescreen space

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#4004] opened 2024-01-24 07:31 UTC
### Describe the feature

- Introduce a widget stack feature inspired by One UI design.
- Enable the stacking of multiple widgets within a single widget.
- Purpose: Save space on the home screen for a cleaner and minimalistic look.
- Enhance user experience by providing an organized and streamlined widget display.

Smart launcher also added this useful feature.

### Why would it be useful to add?

 To save homescreen space

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

https://github.com/LawnchairLauncher/lawnchair/assets/117264003/8ae2d55a-9c6a-4c12-b48f-cb7149921ab6

![IMG_20240124_125832_579](https://github.com/LawnchairLauncher/lawnchair/assets/117264003/9d5629f8-cde8-4126-9588-be8c3dd71350)

**Comment by MrSluffy** [comment] 2024-01-24 08:58
#3956

**Comment by SuperDragonXD** [comment] 2024-01-28 08:45
Hmmm, this issue wasn't closed.

Duplicate of #3956

**Closed as not planned by SuperDragonXD** 2024-01-28 08:45 UTC
Labels: enhancement, feature-request
