### ISSUE TITLE
[BUG]  🚨 Issue with triggering app drawer scroll bar

### ISSUE THREAD

**Issue by Amorphous404** [Deletescape-Media/Lawnchair#3320] opened 2023-02-09 13:35 UTC
### Describe the bug

In Lawnchair v12.1.0 triggering the app drawer **scroll bar ⬆️⬇️** on OnePlus 10 Pro (Curve Display) is a challenge as it cannot be initiated from the edge of the screen, but only from a slight distance away. This makes it harder for me to navigate through my apps with ease and increases the risk of accidentally closing/scrolling the app drawer and adding apps to my home screen.

The issue is persistent on both Stable & Dev Builds; other Launchers, including Lawnchair v2, don't face this issue.

Kindly please address this issue :)

### Steps to reproduce

1. Open "app drawer"
2. Try to swipe/trigger the "scroll bar" from the edge of the screen
3. See "error"

### Expected behavior

The app drawer scroll bar should be instantly activated from the edge of the screen like Lawnchair v2, Alpha Launcher, Niagara Launcher etc

### Screenshots

Lawnchair v12.1.0:
https://user-images.githubusercontent.com/96917972/217826758-38086a59-eac2-48fc-bd04-001c3f126f24.mp4

Lawnchair v2:
https://user-images.githubusercontent.com/96917972/217826787-49e734b1-6fdb-4ee1-81ae-a01d65cd95f4.mp4

### Device information

- Device: OnePlus 10 Pro
- OS: OxygenOS 13
- Andorid Version: Android 13
- App version: 12.1.0 (Dev Build 1630)

**Comment by Goooler** [comment] 2023-02-12 12:59
Duplicate of #3126

**Comment by Goooler** [comment] 2023-02-12 12:59
You can try out the latest debug build from https://github.com/LawnchairLauncher/lawnchair/actions/runs/4153813796

**Closed as completed by Goooler** 2023-02-12 12:59 UTC
Labels: bug
