### ISSUE TITLE
Folders only containing hidden apps are wrongly displayed & crash Lawnchair

### ISSUE THREAD

**Issue by quassy** [Deletescape-Media/Lawnchair#1775] opened 2019-10-12 22:10 UTC
## Description
An app folder only containing hidden apps is wrongly displayed in the app drawer and opening it will reliably crash Lawnchair. I have checked, that there are no similar issues reported before.

## Expected Behavior
* Folders that don't contain any visible apps should not be displayed in the app drawer
* No reasonable action such as opening a folder should crash Lawnchair

## Actual Behavior
* Folder that don't contain any visible apps but only hidden ones are displayed in the app drawer
* Opening that empty folder will crash Lawnchair

## Steps to Reproduce
1. In settings, enable categorization and use the folder feature
2. Create a new folder and add a single app that is hidden from view in the app drawer
3. Check your app drawer
4. The folder is displayed (bug)
5. Opening that folder will crash Lawnchair (bug)

## Environment
* Device: BQ Aquaris X
* Android version: 8.1.0
* Launcher version: 2.0-2497
* Rom: Stock

**Comment by navhaxs** [comment] 2019-10-24 10:37
I found that this bug also manifests when there is a Work profile (Android for Work) set up, and a folder is created which only contains apps which exist in the Personal profile.

To reproduce:
1. Install [Island](https://island.oasisfeng.com/) or [Shelter](https://f-droid.org/en/packages/net.typeblog.shelter/) to create a Work profile if you don't already have one set up.
2. Create a new folder and add a single app that exists only in the Personal profile. (i.e. any app which is not installed in the Work profile.
3. Open the app drawer
5. The folder is correctly displayed on the 'Personal' tab
4. Tap on the 'Work' tab
5. The folder is still displayed even though it is now empty (bug)
6. Opening that folder will crash Lawnchair (bug)

**Comment by navhaxs** [comment] 2019-10-27 11:06
For a fix for this, I am supposing that for whichever code that is generating the menu items, it just needs an additional check for a folder item: to skip it if there are no visible apps inside that folder.

I was able to do an alpha build from the git repo, so if no-one is working on this I am interested in having a go.

**Comment by ghost** [comment] 2021-11-12 21:49
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.

**Closed as completed by ghost** 2021-11-12 21:49 UTC
Labels: bug

**Comment by KevinTyrrell** [comment] 2022-01-02 00:03
Encountered this bug on Lawnchair 12 on accident. How to reproduce:

* Create a folder.
* Add any number of apps into said folder.
* For each app added, hide said app in the 'Drawer' settings.
* Open app drawer and observe your folder is now transparent with text below it.
* Open the folder

This will cause Lawnchair to crash.

Solution: do not hide apps which are inside of folders (expected behavior)

**Comment by RikKoedoot** [comment] 2022-01-02 09:46
Could you screen record this issue? As it doesn't happen here
