### ISSUE TITLE
[BUG] Crash, Surface Duo

### ISSUE THREAD

**Issue by Hammerfest** [Deletescape-Media/Lawnchair#2861] opened 2022-08-22 06:13 UTC
### Describe the bug

Open app drawer, app crash.

### Steps to reproduce

Install
Open app drawer
Crash

### Expected behavior

Open App drawer 

### Device information

- Device: Surface Duo
- OS: Stock A11
- App version Latest Alpha as of this ticket 

### Additional context

Lawnchair bug report Aug 22, 2022 1:07:55 AM
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: surface
build.device: duo
build.display: 2022.519.29
build.fingerprint: surface/duo/duo:11/2022.519.29/202205190029:user/release-keys
build.hardware: surfaceduo
build.id: 2022.519.29
build.manufacturer: Microsoft
build.model: Surface Duo
build.product: duo
build.type: user
version.codename: REL
version.incremental: 202205190029
version.release: 11
version.sdk_int: 30
display.density_dpi: 400
isRecentsEnabled: false

error: Uncaught exception

java.lang.IllegalArgumentException: Animators cannot have negative duration: -248
	at android.animation.ValueAnimator.setDuration(ValueAnimator.java:598)
	at android.animation.ObjectAnimator.setDuration(ObjectAnimator.java:910)
	at android.animation.ObjectAnimator.setDuration(ObjectAnimator.java:71)
	at com.android.launcher3.anim.PendingAnimation.add(PendingAnimation.java:4)
	at com.android.launcher3.anim.PendingAnimation.add(PendingAnimation.java:3)
	at com.android.launcher3.allapps.AllAppsTransitionController.setStateWithAnimation(AllAppsTransitionController.java:10)
	at com.android.launcher3.allapps.AllAppsTransitionController.setStateWithAnimation(AllAppsTransitionController.java:1)
	at com.android.launcher3.statemanager.StateManager.createAnimationToNewWorkspaceInternal(StateManager.java:4)
	at com.android.launcher3.statemanager.StateManager.createAnimationToNewWorkspace(StateManager.java:9)
	at com.android.launcher3.uioverrides.touchcontrollers.PortraitStatesTouchController.initCurrentAnimation(PortraitStatesTouchController.java:24)
	at com.android.launcher3.uioverrides.touchcontrollers.NoButtonNavbarToOverviewTouchController.initCurrentAnimation(NoButtonNavbarToOverviewTouchController.java:1)
	at com.android.launcher3.touch.AbstractStateChangeTouchController.reinitCurrentAnimation(AbstractStateChangeTouchController.java:11)
	at com.android.launcher3.touch.AbstractStateChangeTouchController.onDragStart(AbstractStateChangeTouchController.java:7)
	at com.android.launcher3.uioverrides.touchcontrollers.NoButtonNavbarToOverviewTouchController.onDragStart(NoButtonNavbarToOverviewTouchController.java:1)
	at com.android.launcher3.touch.SingleAxisSwipeDetector.reportDragStartInternal(SingleAxisSwipeDetector.java:2)
	at com.android.launcher3.touch.BaseSwipeDetector.reportDragStart(Unknown Source:0)
	at com.android.launcher3.touch.BaseSwipeDetector.setState(BaseSwipeDetector.java:7)
	at com.android.launcher3.touch.BaseSwipeDetector.onTouchEvent(BaseSwipeDetector.java:23)
	at com.android.launcher3.touch.AbstractStateChangeTouchController.onControllerTouchEvent(Unknown Source:2)
	at com.android.launcher3.touch.AbstractStateChangeTouchController.onControllerInterceptTouchEvent(AbstractStateChangeTouchController.java:8)
	at com.android.launcher3.uioverrides.touchcontrollers.PortraitStatesTouchController.onControllerInterceptTouchEvent(PortraitStatesTouchController.java:6)
	at com.android.launcher3.views.BaseDragLayer.findControllerToHandleTouch(BaseDragLayer.java:5)
	at com.android.launcher3.views.BaseDragLayer.findActiveController(BaseDragLayer.java:3)
	at com.android.launcher3.views.BaseDragLayer.onInterceptTouchEvent(BaseDragLayer.java:6)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2664)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:13)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:2)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:503)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1922)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:6)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:461)
	at android.view.View.dispatchPointerEvent(View.java:14582)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6159)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5962)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5453)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5510)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5476)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5628)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5484)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5685)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5457)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5510)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5476)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5484)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5457)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8266)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8174)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8135)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8458)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8415)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8497)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:724)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7724)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Hammerfest** [comment] 2022-08-22 06:16
Can someone merge with 2562, same issue, did not load in initial search due to phone mistype

**Comment by SuperDragonXD** [comment] 2022-08-23 04:21
Okay, will mark as a duplicate of #2562

**Closed as completed by SuperDragonXD** 2022-08-23 04:21 UTC
Labels: bug
