### ISSUE TITLE
[FR] Set custom icon from gallery

### ISSUE THREAD

**Issue by KabbAmine** [Deletescape-Media/Lawnchair#462] opened 2017-08-09 10:32 UTC
Thanks for making such wonderful launcher.

Something I miss from other launchers (adw2 is my favourite) is the ability to set  normal pictures as an icons. I often create my own custom icons and add them manually to the desktop/drawer apps.

Can you add this feature?

**Comment by nyancrimew** [comment] 2017-08-09 10:45
duplicate of #434

**Closed as completed by nyancrimew** 2017-08-09 10:45 UTC

**Comment by KabbAmine** [comment] 2017-08-09 10:52
My bad, duplicate of a duplicate :) Strange that I didn't find those issues when searching.
