### ISSUE TITLE
Lawnchair crashes on Oppo ColorOS

### ISSUE THREAD

**Issue by hsehdar** [Deletescape-Media/Lawnchair#1961] opened 2020-03-15 09:49 UTC
## Description
All of a sudden from today there was Lawnchair notifications that it had crashed.

## Expected Behavior
Do not crash.

## Actual Behavior
I couldn't notice any difference however.

## Steps to Reproduce
Don't know how to reproduce.

## Environment
* Device: Oppo F9
* Android version: 9.0.0
* Launcher version: 2.0-2589 (2589)
* Rom: ColorOS 6

## Error
```
Lawnchair bug report Mar 15, 2020 12:47:28 PM
Lawnchair version: 2.0-2589 (2589)
build.brand: OPPO
build.device: CPH1823
build.display: CPH1823EX_11_C.16
build.fingerprint: OPPO/CPH1823/CPH1823:9/PPR1.180610.011/1574089662:user/release-keys
build.hardware: mt6771
build.id: PPR1.180610.011
build.manufacturer: OPPO
build.model: CPH1823
build.product: CPH1823
build.type: user
version.codename: REL
version.incremental: 1574072319
version.release: 9
version.sdk_int: 28

error: Uncaught exception

--------- beginning of stacktrace
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.content.res.Resources.getDrawableForDensity(int, int, android.content.res.Resources$Theme)' on a null object reference
	at android.appwidget.AppWidgetProviderInfo.loadDrawable(AppWidgetProviderInfo.java:425)
	at android.appwidget.AppWidgetProviderInfo.loadPreviewImage(AppWidgetProviderInfo.java:354)
	at com.android.launcher3.WidgetPreviewLoader.generateWidgetPreview(WidgetPreviewLoader.java:2)
	at com.android.launcher3.WidgetPreviewLoader.generatePreview(WidgetPreviewLoader.java:2)
	at com.android.launcher3.WidgetPreviewLoader.access$000(WidgetPreviewLoader.java:1)
	at com.android.launcher3.WidgetPreviewLoader$PreviewLoadTask.doInBackground(WidgetPreviewLoader.java:17)
	at com.android.launcher3.WidgetPreviewLoader$PreviewLoadTask.doInBackground(WidgetPreviewLoader.java:1)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by lexmephi** [comment] 2020-08-14 07:34
The same error, but i know steps to reproduce:
1. Print in google search "wheather"
2. Expand the widget
3. Open sandwich menu and choose "add to home screen"
4. Enjoy

**Comment by RikKoedoot** [comment] 2021-08-27 11:46
Closing because effort has been moved to v11

**Closed as completed by RikKoedoot** 2021-08-27 11:46 UTC
