### ISSUE TITLE
Switch between original Pixel and Pixel 2 styles

### ISSUE THREAD

**Issue by thecyclichedgehog** [Deletescape-Media/Lawnchair#962] opened 2017-11-22 06:46 UTC
## Description

Make it possible to switch between original Pixel launcher style to Pixel 2's. I mean search bar in Doc area and calendar/weather/alarm widget in top

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by nyancrimew** [comment] 2017-11-22 07:46
Duplicate of #811

**Closed as completed by nyancrimew** 2017-11-22 07:46 UTC

**Comment by guest4711** [comment] 2017-11-22 10:08
But #811 is not open anymore..  (closed 2017/10)
