### ISSUE TITLE
[FR] Allow user to select Default Homescreen

### ISSUE THREAD

**Issue by zilexa** [Deletescape-Media/Lawnchair#1846] opened 2019-12-01 21:52 UTC
Please allow selecting a default homescreen via the "Organise screens" option when long pressing on a screen. 
Currently, the default homescreen is always the most left screen.

**Comment by thewithz** [comment] 2019-12-03 19:58
This issue is a duplicate of #75 and #702

**Comment by OpenWarp** [comment] 2020-03-14 20:18
I agree. At the very least an option must exist to substitute Google feed with the widget of choice.

**Comment by zilexa** [comment] 2020-05-17 09:31
Is this still being considered to be implemented or already decided and just waiting for priority to be assigned? I am just asking, as I read through the older issues and noticed a statement was made Google once removed this feature from Pixel Launcher so it shouldn't be in Lawnchair.

With that strange logic, you could remove all features from Lawnchair that are not in the official Launcher.

Please, please add this feature in the next release.

**Comment by Elaborendum** [comment] 2022-08-22 00:21
I don't think this has been added yet.

**Comment by SuperDragonXD** [comment] 2022-08-23 06:16
Superseded by #2683

**Closed as completed by SuperDragonXD** 2022-08-23 06:16 UTC
