### ISSUE TITLE
Recent Apps

### ISSUE THREAD

**Issue by MrMargouillat** [Deletescape-Media/Lawnchair#490] opened 2017-08-12 12:52 UTC
A feature I would love to have is the first line of the app drawer to show the most used or the latest apps opened.

**Comment by stefanoantonel** [comment] 2017-08-12 13:21
I like the idea but I'd suggest this as a optional item.

**Comment by intelligentcasanova** [comment] 2017-08-12 13:33
Duplicate of #62.
Please search existing issues before opening a new one.

**Closed as completed** 2017-08-13 03:14 UTC
