### ISSUE TITLE
Search For icons 

### ISSUE THREAD

**Issue by SebinChacko** [Deletescape-Media/Lawnchair#823] opened 2017-10-12 07:33 UTC
Can you add the possibility to search icon by name in layout where all the icons are displayed
For devices running from Marshmallow 6.0.1

**Comment by fonix232** [comment] 2017-10-12 13:48
This has been requested multiple times. Opening new issue tickets won't bring this issue to the top of the queue. Duplicate of #665

**Closed as completed by fonix232** 2017-10-12 13:48 UTC
