### ISSUE TITLE
Possible bug: App icons removed/uncategorized on update

### ISSUE THREAD

**Issue by carenrose** [Deletescape-Media/Lawnchair#2042] opened 2020-08-21 18:38 UTC
Unfortunately I don't have more detailed info as I didn't notice right away when it happened.

I had the KeePass app in my dock, with a custom icon chosen, and categorized in the app drawer. 

The (KeePass) app auto-updated yesterday from the Play store. My phone also did an Android system update.

After the reboot I noticed:
- two icons were removed from my dock, KeePass and another that did not get updated
- In the app drawer, KeePass was no longer in a category

Lawnchair version 2.0-2589
Android 10

**Comment by elmacci** [comment] 2020-10-06 14:50
I am having a simililar issue.
Shortcuts of specific apps on the homescreen do disappear after a while - it is reproducable when e.g. changing the icon pack, updating an app etc. (obviously every action that triggers a "refresh" of the homescreen).

I narrowed it down to the following apps / types of apps:

1) Apps which can disable / enable themselves to appear as an app in the launcher / drawer. For example, the Weather App, Reminder App and Secure Folder App on Samsung devices are not visible as apps from the beginning, but you can enable them by going into their respective settings and enable the option "show in app drawer".
These apps are affected by this bug. I guess every other app which has this functionality is affected as well, but - its just speculative.

2) Apps which can alter their app icon themselves without using an icon pack. For example, the music player "poweramp" has the option to change the appearance of the drawer app icon from the standard look to a white look, a black look etc. When using this option in the poweramp settings, the app shortcut on the homescreen is affected by the same bug / behaviour as described.
When setting the standard app icon within the poweramp app again, this bug does not affect the poweramp app again.

Lawnchair version 2.0-2589
Android 10
Samsung Galaxy Note 20 Ultra 5G

**Comment by RikKoedoot** [comment] 2021-08-27 11:19
Closing because effort has been moved to v11

**Closed as completed by RikKoedoot** 2021-08-27 11:19 UTC
