### ISSUE TITLE
Please provide option to remove search bar in app drawer.

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1282] opened 2018-06-26 19:40 UTC
## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by nyancrimew** [comment] 2018-06-26 19:41
@QuintinAnderson Duplicate of other issues, closed

**Closed as completed** 2018-06-28 08:15 UTC
