### ISSUE TITLE
support new navbar gestures

### ISSUE THREAD

**Issue by E663568** [Deletescape-Media/Lawnchair#2016] opened 2020-07-06 14:48 UTC
Pls support the new navbar gestures i like it and i like the launcher yours also support it pls (this should be a feature comment or something)

**Comment by kinesight** [comment] 2020-07-07 07:13
> Pls support the new navbar gestures i like it and i like the launcher yours also support it pls (this should be a feature comment or something)

What version are you using ? On what Android ?

**Comment by Cyanic76** [comment] 2020-07-09 19:58
most likely android 10 or some miui

**Comment by adi-g15** [comment] 2020-07-11 13:46
Possible duplicate of issue #1733.

**Comment by ghost** [comment] 2021-11-19 15:43
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.

**Closed as completed by ghost** 2021-11-19 15:43 UTC
