### ISSUE TITLE
New Pixel Launcher Home UI

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#804] opened 2017-10-05 14:02 UTC
As from yesterday most of us saw the google presentation of 2017 products and ofcourse Pixel 2 that is coming with the all new Launcher UI. This is a video presentation, and i am wondering, how possible is it to implement all these new characteristics to Lawnchair (like bottom search bar, glansh info date weather widget on top, google bar in app drawer etc)

https://www.youtube.com/watch?time_continue=132&v=iOstm6va_pw

Is there anyone how can leak the official launcher apk (modded for lower that android 8.0) for testing??

**Comment by nyancrimew** [comment] 2017-10-05 15:56
Duplicate of #786

**Closed as completed by nyancrimew** 2017-10-05 15:56 UTC
