### ISSUE TITLE
App icon in recents is not masked correctly

### ISSUE THREAD

**Issue by LuminarySage** [Deletescape-Media/Lawnchair#1653] opened 2019-07-15 04:57 UTC
## Description

Lawnchair masks the urban dictionary app icon correctly in the desktop and app drawer but not in recent apps. The screenshot below shows both the correctly and incorrectly masked icon (the correct one is in the recent apps dock).

## Steps to Reproduce

1. Get the official urban dictionary app
2. Enable automatic adaptive icons for all apps in theme settings
3. Open urban dictionary
4. Go to recent apps

## Environment

* Device: OnePlus 6
* Android version: 9.0
* Launcher version: 2315
* Rom: OOS 9.0.3

![Screenshot_20190715-004758](https://user-images.githubusercontent.com/24306400/61196122-759e6500-a69a-11e9-8c2d-9b086246a323.jpg)

**Comment by nyancrimew** [comment] 2019-07-23 01:37
Duplicate of #1563

**Closed as completed by nyancrimew** 2019-07-23 01:37 UTC
