### ISSUE TITLE
[BUG] Widgets not functioning properly on my OnePlus 9 Pro.

### ISSUE THREAD

**Issue by balaclavatechnical** [Deletescape-Media/Lawnchair#2972] opened 2022-09-20 09:37 UTC
### Describe the bug

Lawnchair always crashes when putting a widget on my OnePlus 9 Pro.

### Steps to reproduce

1. Long press on home page
2. Click on 'Widgets'
3. Scroll down to 'Google (for example)'
4. Click on 'At a glance'
5. See error

### Expected behavior

I expect the widget to remain on my home screen with no problems at all.

### Device information

- Device: [OnePlus 9 Pro]
- OS: [Stock ROM Android version 12.0]
- App version: [12.1.0 Alpha 4]

### Additional context

Lawnchair bug report 20 Sept 2022 11:24:35
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: OnePlus
build.device: OnePlus9Pro
build.display: LE2125_11_C.63
build.fingerprint: OnePlus/OnePlus9Pro/OnePlus9Pro:12/RKQ1.211119.001/R.202208121853:user/release-keys
build.hardware: qcom
build.id: RKQ1.211119.001
build.manufacturer: OnePlus
build.model: LE2125
build.product: OnePlus9Pro
build.type: user
version.codename: REL
version.incremental: R.202208121853
version.release: 12
version.sdk_int: 31
display.density_dpi: 640
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference in method 'void com.android.launcher3.Launcher.completeAddAppWidget(int, com.android.launcher3.model.data.ItemInfo, android.appwidget.AppWidgetHostView, com.android.launcher3.widget.LauncherAppWidgetProviderInfo)'
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:563)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1230)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:366)
	at android.view.Choreographer.doFrame(Choreographer.java:913)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by Goooler** [comment] 2022-09-27 08:06
Duplicate of #2820

**Closed as not planned by Goooler** 2022-09-27 08:06 UTC
Labels: bug
