### ISSUE TITLE
Widgets crashing again

### ISSUE THREAD

**Issue by El-Castellano** [Deletescape-Media/Lawnchair#2312] opened 2021-11-05 07:06 UTC

**Comment by GatherStar** [comment] 2021-11-06 08:17
Lawnchair bug report 2021年11月6日 16:17:33
version: 12.0 Alpha 3 (120003)
commit: 7e4d7bb
build.brand: samsung
build.device: gts6lwifi
build.display: RP1A.200720.012.T860XXU4CUI4
build.fingerprint: samsung/gts6lwifixx/gts6lwifi:11/RP1A.200720.012/T860XXU4CUI4:user/release-keys
build.hardware: qcom
build.id: RP1A.200720.012
build.manufacturer: samsung
build.model: SM-T860
build.product: gts6lwifixx
build.type: user
version.codename: REL
version.incremental: T860XXU4CUI4
version.release: 11
version.sdk_int: 30
display.density_dpi: 360

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference
	at com.android.launcher3.Launcher.completeAddAppWidget(Unknown Source:18)
	at com.android.launcher3.Launcher$4.run(Unknown Source:9)
	at com.android.launcher3.Workspace$6.run(Unknown Source:12)
	at com.android.launcher3.dragndrop.DragLayer$2.onAnimationEnd(Unknown Source:4)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:740)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:247)
	at android.app.ActivityThread.main(ActivityThread.java:8618)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by RikKoedoot** [comment] 2022-01-12 18:22
closing because closing because of duplicate of #2277

**Closed as completed by RikKoedoot** 2022-01-12 18:22 UTC
