### ISSUE TITLE
Google Button in top disappears and is unresponsive

### ISSUE THREAD

**Issue by Xyolyp** [Deletescape-Media/Lawnchair#239] opened 2017-07-18 06:17 UTC
Sometimes nur I can't tell when, the Google pill won't reakt to taps or won't even show up at all on screen.
I have a Nexus 6P with stock Android 7.1.2

**Comment by RWOne** [comment] 2017-07-18 14:25
Sometimes backing out after making a change to the app it no longer shows, in this cases I just went to debug and restarted the app.

**Comment by Xyolyp** [comment] 2017-07-18 14:39
It appears randomly after I unlock my phone or press the home button while having any app opened. I guess it hapens sometimes eben the launcher initialises.

**Comment by abtExp** [comment] 2017-07-20 17:27
Facing similar issues, the pill disappears and I've to go to settings and toggle it to make it reappear (on Moto g 2014(titan))

**Comment by Younes-L** [comment] 2017-07-25 17:55
Similar issue with the rounded search bar here

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment] 2017-07-25 17:57
Btw isn't this a duplicate of #27 ?

**Comment by Xyolyp** [comment] 2017-07-25 18:05
@Younes-L No we don't talk about the notification stuff on the icons but the search pill in the top left corner on the homescreen.

**Comment by Younes-L** [comment] 2017-07-25 19:22
@Xyolyp https://github.com/Deletescape-Media/Lawnchair/issues/27#issuecomment-308840709

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Xyolyp** [comment] 2017-07-25 19:24
@Younes-L I'm sorry, you are right

**Closed as completed** 2017-07-26 09:24 UTC
