### ISSUE TITLE
Canvas A1 (Android One) Phone 

### ISSUE THREAD

**Issue by gratianm** [Deletescape-Media/Lawnchair#522] opened 2017-08-14 07:05 UTC
Dear Sir, love and respect your work. I have one bug since the day of your first release! When I force on the center icon of the dock, half of the information goes out of the screen! Please refer this link for the screen shot! https://goo.gl/rcq67h
 My phone Model: Micromax Canvas A1 running on stock Android marshmallow 6.0.1

**Comment by intelligentcasanova** [comment] 2017-08-14 08:40
Duplicate of #212.
Please close this issue.

**Closed as completed** 2017-08-14 08:45 UTC
