### ISSUE TITLE
Icon pack bug stuck on System in Sesame app

### ISSUE THREAD

**Issue by GhostCod3** [Deletescape-Media/Lawnchair#1907] opened 2020-01-15 06:45 UTC
## Description

There a bug with the icon pack settings  in Sesame app with Lawnchair 2, when I restarted my phone after the first time I installed the Sesame app, the icons go back to default system pack and when I tried to change it back in Sesame settings "look & feel">"Icon pack" The icons package I choose is not selected and is stuck on "System" icon pack.
In Reddit "Sesame channel" they said: "We put in a feature that would sync the icon pack from the launcher and Lawnchair seems to have a bug connected with that."
And they ask me to report to you about the bug.

## Expected Behavior

It should stay on the Icons package in Sesame app I chose and not return to the default icons .

## Actual Behavior

After I restarted my phone the icons pack in Sesame "look and Feel" settings go back to default icons because is sync the icon pack from the Lawnchair. And I can't change it because is stuck on "system".

## Steps to Reproduce

https://vimeo.com/384556903

## Environment

* Device: xaomi pocophone f1
* Android version: 9.0.0
* Launcher version: 2.0-2589
* Rom: MIUI Global 11.0.5 | Stable
11.0.5.0(PEJMIXM)
* Sesame version: 3.6.2-beta1/build 14891

**Comment by pandajammies** [comment] 2020-01-16 19:22
I'm having the same issue. I installed Lawnchair as the previous launcher I used is no longer compatible with the new Android 10 upgrade. But now Lawnchair won't change from the default system icons. It's stuck there.

**Comment by GooseCoder** [comment] 2020-02-14 10:06
I've had the same problem with my mi 9t pro and Lawnchair. I fixed by unchecking the following setting: 
Lawnchair Settings > Plugins > "Share Style Settings"
Once done, I could be able to change the icon pack independently on sesame, not sure if this is an issue with Lawnchair or Sesame. But certainly, if the "Share Style Settings" is checked, both should have the same icon pack loaded, this was not the case.

Regards,

**Comment by MezzInshwet** [comment] 2020-06-24 19:29
I am also facing issues like this i am not able to change icon pack on sesame 
My Device **Poco X2** 
Launcher**Lawnchair Launcher**
Please fix this

**Comment by RikKoedoot** [comment] 2022-01-12 18:31
closing this issue as it seems to be an issue with the sesame app

**Closed as completed by RikKoedoot** 2022-01-12 18:31 UTC

**Comment by qumberrizvi** [comment] 2022-03-20 22:49
> I've had the same problem with my mi 9t pro and Lawnchair. I fixed by unchecking the following setting: Lawnchair Settings > Plugins > "Share Style Settings" Once done, I could be able to change the icon pack independently on sesame, not sure if this is an issue with Lawnchair or Sesame. But certainly, if the "Share Style Settings" is checked, both should have the same icon pack loaded, this was not the case.
> 
> Regards,

This fixes the issue. Looks like the problem is in the Lawnchair integration of Sesame.
