### ISSUE TITLE
Lawnchair request 26

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#80] opened 2017-06-28 02:25 UTC
BUG: (v198) When selecting app icons to move them, Lawnchair freezes for about a second. (It's probably because of the new app shortcut dialogue. In case I didn't mention this earlier, also support Android Nougat app shortcuts, like Nova Launcher does)

**Comment by r4lex** [comment] 2017-06-28 14:21
I can confirm I have the same behavior right now.

**Comment by tstackhouse** [comment] 2017-06-28 14:47
Duplicate of #76?

**Comment by r4lex** [comment] 2017-06-28 15:25
Yes, I think so.

**Comment by OvermindDL1** [comment] 2017-06-28 15:31
Please, @Dondrejohnson5, for the sake of all Github Issue trackers, please please please use proper Issue names.  ^.^;

`Lawnchair request 26` is entirely non-descriptive and is entirely useless when tracking.  ^.^;

**Comment by deletescape** [comment] 2017-06-28 19:22
@tstackhouse exactly, closing for being a duplicate

**Closed by deletescape** 2017-06-28 19:22 UTC
Labels: duplicate
