### ISSUE TITLE
Per-app icon change

### ISSUE THREAD

**Issue by Ostatni** [Deletescape-Media/Lawnchair#25] opened 2017-06-15 17:12 UTC
Hello

Can you add icon change per-app? Taking app from drawer giving only to us 2 option- invisible app or change name

**Comment by deletescape** [comment] 2017-06-15 17:17
Closing this issue as it is a duplicate of #6

**Closed by deletescape** 2017-06-15 17:17 UTC

**Comment by Ostatni** [comment] 2017-06-15 17:28
Oh sorry didn't know it is it.
