### ISSUE TITLE
[FEATURE] android 13 quickstep

### ISSUE THREAD

**Issue by dot166** [Deletescape-Media/Lawnchair#3601] opened 2023-08-25 18:07 UTC
### Describe the feature

lawnchair would have support for android 13 quickstep api

### Why would it be useful to add?

trebuchet is rubbish so i would like lawnchair to be able to support android 13 quickstep

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

recents menu but lawnchair providing it

**Comment by osm0sis** [comment] 2023-08-30 01:03
Duplicate of https://github.com/LawnchairLauncher/lawnchair/issues/3249

**Closed as completed** 2023-08-30 06:40 UTC
Labels: enhancement, feature-request
