### ISSUE TITLE
Feature Request - Alternate weather providers

### ISSUE THREAD

**Issue by nonyonah** [Deletescape-Media/Lawnchair#2757] opened 2022-07-09 16:25 UTC
I think it'll be pretty cool if there are alternate weather providers just like on LC 10. The Google app has been buggy lately when it comes to weather and I find myself always going on the internet to check out the weather. Alternate weather providers such as AccuWeather will be great as a fallback incase Google weather doesn't work.

**Comment by SuperDragonXD** [comment] 2022-08-12 15:45
Late reply, but this issue is a duplicate of #2626

**Closed as completed by SuperDragonXD** 2022-08-12 15:45 UTC
