### ISSUE TITLE
Lawnchair is not functional on Android 8.0.0 (bullhead-opr6.170623.0) (using Nexus 5X)

### ISSUE THREAD

**Issue by andreipaciurca** [Deletescape-Media/Lawnchair#582] opened 2017-08-23 12:27 UTC

**Comment by Younes-L** [comment] 2017-08-23 13:44
More details ? What doesn't work for you ?

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment] 2017-08-23 13:44
Also duplicate of #581

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zfm99** [comment] 2017-08-23 13:51
If you update to 8.0 without ever having installed Lawnchair and then install Lawnchair it is completely black and the only thing you can interact with is the notification bar. Long holding to try to access settings doesn't work.

**Comment by Younes-L** [comment] 2017-08-23 14:03
Make sure it is set as default home app from settings, see if that helps ?

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zfm99** [comment] 2017-08-23 14:05
I'm not sure if it does. I did a bunch of stuff but and finally got it working last night but now my weather app doesn't update

**Comment by Younes-L** [comment] 2017-08-23 16:51
@zfm99 interesting...

Try and remove all kinds of battery optimization and background restrictions applied to Lawnchair from settings, see if that helps ?

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Younes-L** [comment] 2017-08-23 16:52
Btw what did you do to fix the non functional issue ?

Other users could benefit from your solution :)

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zfm99** [comment] 2017-08-23 17:00
I granted all permissions before hand, set it as my home launcher and then restarted it

**Comment by thomas-holmes** [comment] 2017-08-23 23:11
After I set it as my launcher it hung for a very long time in a blank screen with just the bottom access buttons. After crashing a few times and waiting for a while it finally started to work. Took about 5 minutes total.

**Comment by suphon-t** [comment] 2017-08-24 10:40
Lawnchair version?

**Comment by asaf666** [comment] 2017-08-24 10:53
I can confirm that installing it , not opening the app, granting all permissions and than opening it solves this problem. Guess it's just because it was first time install and not the fact that it was Android 8

**Comment by thomas-holmes** [comment] 2017-08-24 12:59
1.0.1063

**Comment by callmefido** [comment] 2017-08-24 15:16
Lawnchair (v1.0.1063) mostly works for me on on my 6p with 8.0.0 final. Items that just do not work so far are: 
Notification badges and preview
Dock uses wallpaper colors
Extract accent color from wallpaper

**Comment by ghost** [comment] 2017-08-25 03:57
On my Nexus 6P, notification badges are working fine. This app actually doesn't apply settings properly. If you change some seeing and it doesn't get applied, clear the app's data and try again. It's just unpredictable. So, keep trying to apply what you want.

**Comment by ghost** [comment] 2017-08-25 03:58
*some setting

**Comment by crecsky** [comment] 2017-08-25 14:14
- Google Pixel.
- Android 8.0.0.
- Installed Lawnchair, gave all permissions, set as 'Home' app, set to 'Battery Settings' to 'Not Optimized', set "Install unknown apps' to 'Allowed'.
- Still does not work. When I push the home button it just goes to my home page and it's blank, only showing my wallpaper. It just sits like that then defaults back to my original launcher.
- Even after a reboot it does the same thing.

**Comment by ctnlaring** [comment] 2017-08-28 23:00
Latest lawnchair doesn't work for me on my 6p with Oreo final. I just see a black screen.

**Comment by 5haney** [comment] 2017-08-31 07:40
I find after the initial failure to start I have to set another launcher as default, clear all lawnchair data then switch back to lawnchair and it works from then on.

**Comment by crecsky** [comment] 2017-08-31 13:53
"I find after the initial failure to start I have to set another launcher as default, clear all lawnchair data then switch back to lawnchair and it works from then on." Doesn't work for me.

I'm fine just waiting for the next release and hoping that it's working, all these workarounds are so blah.

**Comment by 5haney** [comment] 2017-09-04 10:03
The clearing data thing no longer works for me, nor does setting permissions first.
Seems to be a lot of different problems with it android O

**Comment by woohooatb** [comment] 2017-09-09 22:35
I did everything people said above but it is still not working for me. I hope dev will fix it soon. Meanwhile check this https://github.com/amirzaidi/Launcher3 
This one is working on Oreo releases but it has a lot less features.

**Comment by michel-slm** [comment] 2017-09-15 21:30
FWIW the Telegram group seems to suggest installing version 818, opening it once and then installing the latest. Not sure why that works (I'm on 7.1.1, can't test) but that might help pinpoint the issue.

**Comment by crecsky** [comment] 2017-09-15 21:33
Edit: Edit: Wait, yes it does.

**Comment by 4RK4N** [comment] 2017-09-17 20:01
indeed installing v818, starting it and then update to  1.1.0.1258 works. but not that simple. that ended in just the wallpaper for ages again. steps i did to get it work
1. install v818
2. start it (press home)
3. go to lancher settings change some stuff (idk what or if that even adds to the fix, did iconpack and black skin and a few others maybe)
4. update to latest version 1.1.0.1258
5. do NOT press home
6. grant it all permissions and force quit it
7. press home
8. it works

nexus 6p september oreo build OPR6.170623.019

hope it gets fixed soon. dont want to a hacky mess like that with the october oreo build again xD
would a logcat of the launcher not starting help? i got it to work, not gonne mess it up again for the log. someone else pls do it :D

**Comment by Younes-L** [comment] 2017-09-18 12:31
@4RK4N  by "do not press home" I assume it also means do not press "open" after installing ?

**Comment by 4RK4N** [comment] 2017-09-18 13:50
press home, press open, whatever. dont start it yet. first give all permissions and force quit.

**Comment by talhek** [comment] 2017-09-21 16:07
Latest versions weren't working on an unofficial Los 15.0 (Oreo) for Oneplus 3T as well. Can confirm though that flashing 818 and then a newer version does work.

**Comment by jtc42** [comment] 2017-10-13 08:46
I'm still getting this issue on 8.0, Nexus 5X, with latest version. Tried granting all permissions before opening etc but hangs on wallpaper for ages. Any way we can get logs or something that might be useful here?

**Comment by divadsn** [comment] 2017-10-17 23:00
Fixed #854

**Closed as completed by divadsn** 2017-10-17 23:00 UTC
Labels: bug, help wanted
