### ISSUE TITLE
Navbar Keys on Galaxy S8 are grey instead of white

### ISSUE THREAD

**Issue by caltas** [Deletescape-Media/Lawnchair#401] opened 2017-08-04 07:54 UTC
![photo5775934069509565103](https://user-images.githubusercontent.com/16832672/28959431-a9deb4f2-78fa-11e7-8b36-ca157624949b.jpg)

On dark backgrounds the keys are barely visible.

😄

**Comment by suphon-t** [comment] 2017-08-06 03:47
Duplicate of #120

**Closed as completed by suphon-t** 2017-08-06 03:47 UTC
