### ISSUE TITLE
Latest Android System Intelligence breaks search in Lawnchair

### ISSUE THREAD

**Issue by ldvk0** [Deletescape-Media/Lawnchair#2334] opened 2021-11-18 02:39 UTC
![Screenshot_20211118-033819_Sklep Google Play](https://user-images.githubusercontent.com/48336657/142341542-46f829a5-22cf-4605-a595-a4d16419df06.png)

If you uninstall updates of this app search in app drawer working again.

**Comment by ldvk0** [comment] 2021-11-18 02:42
![Screenshot_20211118-033819_Sklep Google Play](https://user-images.githubusercontent.com/48336657/142341819-da5c231c-793c-4f7d-99a7-4e57da836bbb.png)
![Screenshot_20211118-034102_Lawnchair](https://user-images.githubusercontent.com/48336657/142341824-5864cb71-1718-4f61-8c38-cff863488b1b.png)


![Screenshot_20211118-034158_Sklep Google Play](https://user-images.githubusercontent.com/48336657/142341897-74e3eaeb-746a-4f30-b410-79c8da5dfb74.png)
![Screenshot_20211118-034205_Lawnchair](https://user-images.githubusercontent.com/48336657/142341902-187ed6a5-b924-4572-99f5-c8ebb88ada80.png)

**Comment by YRSB** [comment] 2021-11-21 14:02
It's fixed in the latest dev build.😉

**Comment by ldvk0** [comment] 2022-01-20 16:07
Issue happening again. Also it causing some apps stuck like Chrome when we set Lawnchair in QuickSwitch as recent provider.

**Comment by RikKoedoot** [comment] 2022-01-20 16:33
**How to get device search to work again:**
1. Uninstall updates for Android System Intelligence.
2. Reboot your device.

**How to detach Android System Intelligence from auto update:**
1. Follow the steps from [this guide.](https://github.com/Magisk-Modules-Repo/Detach#:~:text=Bonus%3A%20To%20detach%20other%20applications%20from%20your%20Play%20Store)
2. Insert "com.google.android.as" into the Detach.txt.

**If you experience the app still getting updated, follow these steps:**
1. Download [terminal emulator.](https://play.google.com/store/apps/details?id=jackpal.androidterm)
2. Type "su -c Detach -t"
3. Choose Crond (2)
4. Choose a time interval of your liking, we recommend 30 minutes (1) interval.
5. Reboot

**Comment by SuperDragonXD** [comment] 2022-08-06 13:49
Closing since this was caused by Google breaking stuff, not Lawnchair. Alongside that, a how to fix guide has been added above (which could be added to the FAQ).

**Closed as completed by SuperDragonXD** 2022-08-06 13:49 UTC
