### ISSUE TITLE
Weather is unstable, at times the launcher hangs

### ISSUE THREAD

**Issue by devang98** [Deletescape-Media/Lawnchair#584] opened 2017-08-23 14:17 UTC
weather is unstable and the launcher hangs at times, it does not do a regular update.

**Comment by zfm99** [comment] 2017-08-23 15:47
Thanks only time my weather is updating is when I restart or the date changes. Restarting the launcher does nothing

**Comment by edwaine** [comment] 2017-08-23 21:00
This issue happened on my Android One G1 device. But not on my Pixel & Nexus 5X though.

**Comment by suphon-t** [comment] 2017-08-23 22:46
Duplicate of #468

**Closed as completed by suphon-t** 2017-08-23 22:46 UTC
