### ISSUE TITLE
Settings crashes on splitscreening in some circumstances

### ISSUE THREAD

**Issue by YoshiRulz** [Deletescape-Media/Lawnchair#1740] opened 2019-09-08 10:10 UTC
## Description
Title.

## Expected Behavior
Splitscreen works, in the same way as it does when you trigger it from the main view (activity? I'm not an android dev).

## Actual Behavior
Crashes with "Lawnchair has stopped" dialog.

## Steps to Reproduce
1. Open Lawnchair Settings > `App drawer` > `Categorization`
2. Hold down recents button

## Environment
* Device: Nexus 5 "hammerhead"
* Android version: 7.1.2
* Launcher version: 2.0-2408
* Rom: LineageOS 14 nightly
edit: just repro'd this on a new phone, now on Lawnchair 2.0-2589.

## Logcat
```
Lawnchair bug report 8 Sep. 2019 18:38:29
Lawnchair version: 2.0-2408 (2408)
build.brand: google
build.device: hammerhead
build.display: lineage_hammerhead-userdebug 7.1.2 NJH47F 1b328df9dc
build.fingerprint: google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys
build.hardware: hammerhead
build.id: NJH47F
build.manufacturer: LGE
build.model: Nexus 5
build.product: hammerhead
build.type: user
version.codename: REL
version.incremental: 1b328df9dc
version.release: 7.1.2
version.sdk_int: 25

error: Uncaught exception

--------- beginning of stacktrace
java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.settings.ui.SettingsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property type has not been initialized
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4556)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property type has not been initialized
	at ch.deletescape.lawnchair.groups.ui.AppCategorizationTypeItem.onValueChanged(AppCategorizationTypeItem.kt:1)
	at ch.deletescape.lawnchair.LawnchairPreferences.addOnPreferenceChangeListener(LawnchairPreferences.kt:4)
	at ch.deletescape.lawnchair.groups.ui.AppCategorizationTypeItem.onAttachedToWindow(AppCategorizationTypeItem.kt:2)
	at android.view.View.dispatchAttachedToWindow(View.java:15513)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4456)
	at android.view.ViewGroup.addView(ViewGroup.java:4258)
	at android.view.ViewGroup.addView(ViewGroup.java:4198)
	at android.view.ViewGroup.addView(ViewGroup.java:4171)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:88)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:6)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:182)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:2)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:6)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6701)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
	... 10 more
```

**Comment by milindgoel15** [comment] 2019-09-08 11:45
I also reproduced but it gave me different reason of the crash. Don't know if both are same

**Comment by TheLBall** [comment] 2019-09-15 22:30
It seems to occur when it's scaled for split screen, as opening an app, going into split screen, opening the affected Lawnchair setting, and closing the first app, leaving Lawnchair Settings, seems to have the same effect.

**Comment by ghost** [comment] 2021-11-18 20:54
This issue will be automatically closed because it doesn’t appear to relate to Lawnchair 12. We don’t provide support for older versions of Lawnchair. If the issue does relate to Lawnchair 12, feel free to reopen it.

**Closed as completed by ghost** 2021-11-18 20:54 UTC
