### ISSUE TITLE
[FEATURE] add to f droid

### ISSUE THREAD

**Issue by RustoMCSpit** [Deletescape-Media/Lawnchair#3552] opened 2023-08-02 01:04 UTC
### Describe the feature

add to f droid

### Why would it be useful to add?

foss community

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

othrr apps

**Comment by KTibow** [comment] 2023-08-11 21:50
Older versions: https://f-droid.org/app/ch.deletescape.lawnchair.plah
Newer versions: this issue is a duplicate of #1473

**Comment by RustoMCSpit** [comment] 2023-08-11 21:59
> Older versions: https://f-droid.org/app/ch.deletescape.lawnchair.plah Newer versions: this issue is a duplicate of #1473

close this then

**Comment by KTibow** [comment] 2023-08-11 22:01
lol im not a project maintainer, i can't close issues
you can close this issue yourself though, see that button right next to the comment button?

**Comment by RustoMCSpit** [comment] 2023-12-13 22:32
not stale

**Closed as not planned** 2024-03-21 00:14 UTC
Labels: enhancement, feature-request

**Comment by Magicrafter13** [comment] 2024-11-10 17:15
> Older versions: https://f-droid.org/app/ch.deletescape.lawnchair.plah Newer versions: this issue is a duplicate of #1473

The problem with #1473 is that it's locked, which is not conducive to discussion. There are still many out there who desire a proper F-Droid build instead of being forced to build the project themselves due to privacy/freedom concerns.
