### ISSUE TITLE
[BUG] QuickSwitch v3.3.1 with Dev v12.1.0 #1473

### ISSUE THREAD

**Issue by MadMan5645** [Deletescape-Media/Lawnchair#3211] opened 2022-12-23 23:36 UTC
### Describe the bug

While using Lawnchair standalone double tap to sleep works fine but after enabling QuickSwitch v3.3.1 double tap to sleep dies and doesn't work. Everything else works as it should though except double tap to sleep. If I remove it as recents provider dt2s will begin to work again but will not work with QuickSwitch enabled 

### Steps to reproduce

1. Install Magisk
2. Install Quickswitch Module
3. Install latest dev build
4. Enable as recents provider
5. Try to use dt2s

### Expected behavior

After enabling the dt2s it should do exactly that. And it does work without being enabled as recents provider.

### Device information

-Device: OnePlus 9 Pro
-Rom: Crdroid v8.x (A12L)
-Lawnchair Build: 12.1.0 #1473

**Comment by osm0sis** [comment] 2022-12-24 00:53
Sounds like a duplicate of #3204

Good to know it works when not Recents provider, that explains how it made it through @yasandev's testing.

**Closed as completed** 2022-12-24 07:18 UTC
Labels: bug
