### ISSUE TITLE
Laggy app drawer scroll

### ISSUE THREAD

**Issue by enricocid** [Deletescape-Media/Lawnchair#1610] opened 2019-06-29 16:50 UTC
## Description

The app drawer scrolling is not fluid.

## Environment

* Device: OnePlus X "onyx"
* Android version: 9.0.0 (POSP ROM)
* Launcher version: it says 9 lol
* Rom: Posp 2.3 (2019.06.10)

## Logcat

[quickstep.txt](https://github.com/LawnchairLauncher/Lawnchair/files/3342105/quickstep.txt)

**Comment by DanGLVK** [comment] 2019-06-29 16:52
That's partially not lawnchair's fault,legacy devices (yes,snapdragon 801 is legacy) have issues with Android Pie's new skiagl renderer which causes signficant/major performance degradation in several apps

Just change your renderer to opengl by adding debug.hwui.renderer=opengl in your build.prop and your ROM will become blazing fast (but some small graphical issues may occur such as the screenshot notification being grey)

**Comment by enricocid** [comment] 2019-06-29 16:54
> That's partially not lawnchair's fault,legacy devices (yes,snapdragon 801 is legacy) have issues with Android Pie's new skiagl renderer which causes signficant/major performance degradation in several apps

Ahh, I understand. That's why the log I provided says almost nothing :) Ok, Thanks for tips. I close then.

**Comment by DanGLVK** [comment] 2019-06-29 16:58
@enricocid tbh lawnchair can "solve" this issue as some launchers did avoid this issue like Hyperion and most stock launchers on pie,there's no need to close the issue as it's still something that lawnchair devs can possibly workaround,it's just that the root of the issue is your device

**Comment by enricocid** [comment] 2019-07-06 06:39
I was trying to investigate the problem looking at other open source launchers that works smoothly. They are based on Oreo branch, maybe also Hyperion which is not open source (I think it is based on rootless launcher like many others out there)... You are the only ones working on the new branch, I think.😁

**Comment by skittles9823** [comment] 2019-07-06 06:41
@enricocid Hyperion is based on launcher3-quickstep iirc. Launcher pretty much need to be to have recents integration working.

**Comment by enricocid** [comment] 2019-07-06 06:46
Thanks @skittles9823 for the super quick reply 😆

**Comment by sktch00** [comment] 2019-07-14 10:41
Experiencing the same issue. Scrolling in the appdrawer is not as fluid compare to other launcher I've tested. Also, I tried adding debug.hwui.renderer=opengl as suggested above doesnt seem to solve the problem. Currently using havocOS latest built on my Xiaomi mi5

**Comment by enricocid** [comment] 2019-07-14 11:17
Is it possible to use different implementations for the app drawer?
What I mean is: Use the old implementation (but with the updated fast scroller) for older devices as it works flawlessy.

**Comment by DontTrustMicrosoft-MicrosoftIsAsshole** [comment] 2019-10-01 20:34
I'd like to add, since lately not only scrolling got choppy, but opening the drawer became a nightmare. it's so slow, you get motion sickness. it wasn't like that before.
device xt1572 , Motorola x style, Android 7

**Closed as completed** 2021-08-27 12:09 UTC
Labels: bug, help wanted
