### ISSUE TITLE
[BUG] Resizing widgets does not resize some sizes

### ISSUE THREAD

**Issue by Rafael2616** [Deletescape-Media/Lawnchair#2584] opened 2022-05-15 16:43 UTC
### Describe the bug

Some widgets don't scale as intended, some don't shrink beyond 2x3 size for example 

### Steps to reproduce

1. Go to 'Widgtes page'
2. Click on 'Any widget'
3. Try Resize

### Expected behavior

Resize widgets to all possible sizes without restrictions

### Screenshots

https://user-images.githubusercontent.com/93414086/168483994-bec115be-d4da-4b9c-9d99-37b0c024594d.mp4

### Device information

- Device: [e.g. Philco PCS01]
- OS: [e.g. stock ROM Android version 9]
- App version [e.g. 12.1 Dev Build #733]

**Comment by kerimgrande** [comment] 2022-05-16 05:12
Didn't happen to me. Are you sure the Widget can go smaller than 2 x 3?

**Comment by Amorphous404** [comment] 2022-08-23 11:25
You can follow #2822, to stay updated about the feature 👍

**Comment by yasanglass** [comment] 2022-10-19 10:41
While this is only partially fixed, I am closing this as it is a duplicate of #2822.

**Closed as completed by yasanglass** 2022-10-19 10:41 UTC
