### ISSUE TITLE
[FEATURE] Add a say to set a home page by default

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#3280] opened 2023-01-23 05:12 UTC
### Describe the feature

Need to be the middle page as home by default when pressing the home button.

### Why would it be useful to add?

Less time sending if the home is on middle page or how anyone is prefer it.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![IMG_20230123_071143](https://user-images.githubusercontent.com/48178307/213969870-46e17864-0537-46cf-8ca7-d0b9c9e70614.jpg)

**Comment by Goooler** [comment] 2023-01-26 05:40
Duplicate of #3127

**Comment by Goooler** [comment] 2023-01-26 05:41
Will track this issue there.

**Closed as not planned by Goooler** 2023-01-26 05:41 UTC
Labels: enhancement, feature-request

**Comment by Goooler** [comment] 2023-01-26 05:47
Duplicate of #2683
