### ISSUE TITLE
Long press options not fitting properly on screen

### ISSUE THREAD

**Issue by jerryn70** [Deletescape-Media/Lawnchair#860] opened 2017-10-18 15:45 UTC
When I long press on icons in home screen and app drawer the options bubble goes out side the screen . ![](https://i.imgur.com/1P4KDus.png)
![](https://i.imgur.com/6OCPMEb.jpg)

Device moto x play
Marshmallow 6.0.1

**Comment by divadsn** [comment] 2017-10-18 16:27
Have you changed DPI settings manually?

**Comment by jerryn70** [comment] 2017-10-18 16:37
no i didn't changed anything

**Comment by nyancrimew** [comment] 2017-10-19 08:16
Duplicate of #535

**Closed as completed by nyancrimew** 2017-10-19 08:16 UTC
