### ISSUE TITLE
widgets page

### ISSUE THREAD

**Issue by ACHOKAMAN** [Deletescape-Media/Lawnchair#230] opened 2017-07-17 13:05 UTC
dear devs i want to request,is it possible to add a widgets page that can replace google now from the left,,,,atleast an option to allow instead of the now page we get a page that is convinient for adding widgets,,,

**Comment by RWOne** [comment] 2017-07-17 14:26
Why?

You have widget picker by long pressing an app now, or a long press of the home screen and select widgets.

I'm it would be wasted space to take up one page.

**Comment by fonix232** [comment] 2017-07-17 15:39
@RWOne I think @ACHOKAMAN  means that we would have a vertically scrolling list of custom widgets - i.e. you can decide what to put into the list, something like the OnePlus Launcher does on their leftmost panel.

**Comment by RWOne** [comment] 2017-07-17 16:14
@fonix232 Haven't seen that myself ...  But I have maybe two widgets in use, so ....   :)

**Comment by AxiK101** [comment] 2017-07-17 16:36
Not a great idea.

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ACHOKAMAN** [comment] 2017-07-18 16:07
@AxiK101  at first all ideas are never great,,,is just like all answers are right as long as you defend them.....we all love diffrent things bro,,,we all come from diffrent OS so when we move we would wish to have something to make us stay and love something more,,,,mine that widgets features ,,,,scrolling one is something am hoping for in the future when request and issue will be implimented.....

**Comment by AxiK101** [comment] 2017-07-18 16:11
@ACHOKAMAN no offense, i think that idea sticks more to oneplus launcher style. Pixel style is deeply connect with google app. 

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment] 2017-08-09 17:48
Duplicate of #110

**Closed as completed** 2017-08-10 05:39 UTC
Labels: feature-request
