### ISSUE TITLE
Hiding apps from the main Apps tab also hides them in any other tab.

### ISSUE THREAD

**Issue by criptixo** [Deletescape-Media/Lawnchair#1511] opened 2019-04-18 16:41 UTC
**Description** 

Hiding apps from the main Apps tab also hides them in any other tab.

**Expected Behavior** 

The apps hidden in "Apps" tab shouldn't be hidden in other sperate tabs so i can per example make a tab for games only.

**Actual Behavior** 

The apps hidden in "Apps" tab don't appear in any other tabs.

Steps to Reproduce

- Create a new Tab and add the device settings app to it.

- Hide the device settings from "Apps" tab. 

**Device**

Device : OnePlus One
Android : 7.1.2
Lawnchair : 2.0-1991-ci-alpha
Rom : LineageOS

**Comment by divadsn** [comment] 2019-04-18 16:45
@criptixo That's expected behavior tbh.

**Comment by suphon-t** [comment] 2019-04-19 02:25
Closing: working as intended.

**Closed as completed** 2019-04-19 02:25 UTC
