### ISSUE TITLE
Smartspacer gets cut off when selecting it as "at a glance" provider

### ISSUE THREAD

**Issue by NiXTheDev** [Deletescape-Media/Lawnchair#4184] opened 2024-04-03 14:02 UTC
### Describe the bug

Smartspacer's at a glance gets cutoff when selected as the "at a glance" provider in lawnchair, while it is definitely not a critical bug, it definitely bugs me
Note: when having multiple pages in at a glance from smartspacer, it's not just the first page that gets cutoff, but all of them do so

### Steps to reproduce

1. Install Lawnchair 14b1
2. Install smartspacer
3. Select smartspacer as the "at a glance" provider
4. Go to lawnchair homescreen
5. Observe the cut off "at a glance"

### Expected behavior

Smartspacer at a glance without any mishaps

### Screenshots

![Screenshot_20240403-163008_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/105677206/c6e6d338-69d6-496c-9d40-18c60222aff4)

### Device information

- Device: Redmi note 11(spesn)
- OS: custom ROM A13 with root via magisk, no quickswitch 
- App version: 14 beta 1

**Comment by 88572** [comment] 2024-04-03 14:12
Duplicate of #4096

**Closed as completed** 2024-04-05 04:39 UTC
Labels: bug
