### ISSUE TITLE
Add an option to Override app closing animation like Stock Android (Slide Down).

### ISSUE THREAD

**Issue by akapu1** [Deletescape-Media/Lawnchair#277] opened 2017-07-22 05:06 UTC
Hi.. I love this launcher... Best one I have ever used.. using this on my Galaxy S8. I have a request:

Kindly add an option to override app closing animation like Stock Android (slide down). In my Galaxy S8 app closing animation is like zoom out.. which is very ugly in my opinion. In nova launcher if I select app animation to reveal I get stock Android like experience... Please add this option... 

Thank you for all you guys have done for us.  

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Chaphasilor** [comment] 2017-07-22 12:38
Would also love this although I'd prefer the zoom out animation instead of the slide down animation or the fade out standard animation on my OnePlus 5

**Comment by CroW-D** [comment] 2017-07-25 04:27
I am also requested it yesterday. Would be nice to see some options to choose from. +1

**Comment by intelligentcasanova** [comment] 2017-08-08 00:03
Duplicate of #68

**Comment by intelligentcasanova** [comment] 2017-08-13 09:00
Duplicate of #68

**Closed as completed** 2017-08-13 11:26 UTC
