### ISSUE TITLE
At a glance widget with clock

### ISSUE THREAD

**Issue by fbfrank** [Deletescape-Media/Lawnchair#1536] opened 2019-04-28 10:29 UTC
## Description
Wrong application assignment

## Expected Behavior
Tap on the clock should open the clock app

## Actual Behavior
Tap opens the calendar app

## Steps to Reproduce
Screenshot:
https://photos.app.goo.gl/2GuDBenKdqF3vaHL8

## Environment
* Device: Pixel 3
* Android version: 9.0.0 -->
* Launcher version: 2.1.0 --> 
* Rom: Stock

## Logcat

 

```
your log here
```

**Comment by divadsn** [comment] 2019-04-28 11:50
Duplicate of #1508, please use the search before!

**Closed as completed by divadsn** 2019-04-28 11:50 UTC
