### ISSUE TITLE
Need the missing option to change "individual app icon".

### ISSUE THREAD

**Issue by kryptoncypher** [Deletescape-Media/Lawnchair#2301] opened 2021-11-02 06:49 UTC
I've been using lawnchair since android 9 and i really love the way they try to match with the stock ones. But, I don't want it to be purely stock! And I'm missing one of the important feature "for me" i.e. to change the app icon individually. So, hope they bring back that feature

**Comment by RikKoedoot** [comment] 2021-11-02 07:02
Closing because it's a duplicate of #2201

**Closed as completed by RikKoedoot** 2021-11-02 07:02 UTC
