### ISSUE TITLE
Weird Padding on Long Press Panel

### ISSUE THREAD

**Issue by multiberry** [Deletescape-Media/Lawnchair#629] opened 2017-08-28 12:45 UTC
Whenever I long press an icon in the middle column, the panel seems to hang over the edge of the screen, as shown here: http://imgur.com/SRGAgV9

Device Info
Lenovo Vibe S1
6.0.1 Marshmallow
Latest Lawnchair Alpha

**Comment by amirzaidi** [comment] 2017-08-28 12:59
Use your PC to decrease your DPI with ADB.

**Comment by suphon-t** [comment] 2017-08-28 15:44
Duplicate of #212

**Closed as completed by suphon-t** 2017-08-28 15:44 UTC
