### ISSUE TITLE
The folder icon is not shown in system icon format, only in circle.  The folder icon changes only if you select another application icon format.

### ISSUE THREAD

**Issue by GabrielMGitHub** [Deletescape-Media/Lawnchair#1712] opened 2019-08-18 04:41 UTC
## Description

The folder icon is not shown in system icon format, only in circle.  The folder icon changes only if you select another application icon format.

![Screenshot_20190818-013443_Lawnchair](https://user-images.githubusercontent.com/8754997/63220191-e680e300-c158-11e9-9b35-bef3a39f2a0e.jpg)
![Screenshot_20190818-013508_Lawnchair](https://user-images.githubusercontent.com/8754997/63220192-ec76c400-c158-11e9-8b1b-52e5167a9e4f.jpg)

## Expected Behavior

Look up

## Actual Behavior

Look up

## Steps to Reproduce

Look up

## Environment

* Device:
* Android version: 9.0
* Launcher version: 2.0-2357-ci-alpha
* Rom: Samsung Stock Rom S8+ One UI 1.0

## Logcat

 

```
your log here
```

**Comment by suphon-t** [comment] 2019-08-18 04:44
The template is there for you to fill it, not to put "look up" there.

**Comment by GabrielMGitHub** [comment] 2019-08-18 04:49
> The template is there for you to fill it, not to put "look up" there.

The application icons of the Samsung S8 Plus have this format.
![Screenshot_20190818-013508_Lawnchair](https://user-images.githubusercontent.com/8754997/63220287-5d6aab80-c15a-11e9-9094-724112e3b938.jpg)

**Comment by GabrielMGitHub** [comment] 2019-08-18 04:52
When selecting default system icon, the folder should have the same format as the icons, but it is not, instead showing in a circle, Nova Launcher leaves the folder the same as the default icon format.

**Comment by GabrielMGitHub** [comment] 2019-08-18 04:57
![Screenshot_20190818-015555_Nova Launcher](https://user-images.githubusercontent.com/8754997/63220339-72940a00-c15b-11e9-934b-71743e296b2d.jpg)
![Screenshot_20190818-015630_Nova Launcher](https://user-images.githubusercontent.com/8754997/63220342-79228180-c15b-11e9-92a1-b93b3b00c062.jpg)

**Comment by GabrielMGitHub** [comment] 2019-08-18 04:58
@paphonb 
This needs to be improved not good.

**Comment by suphon-t** [comment] 2019-08-18 16:28
Closing now. See #1715 instead.

**Closed as completed by suphon-t** 2019-08-18 16:28 UTC

**Comment by GabrielMGitHub** [comment] 2019-08-18 16:37
Should set as future enhancement, instead of closing the question, the Nova Launcher has this function why Lawnchair can not have?  This developer is very ignorant as a person and as a developer.

**Comment by DanGLVK** [comment] 2019-08-18 16:43
@GabrielMGitHub your issue was only closed due to it being a duplicate of another issue, your issue also doesn't follow the correct template used for reporting issues

**Comment by GabrielMGitHub** [comment] 2019-08-18 16:52
The other question was also closed, and my question was reported accordingly, only being too retarded not to see it.  Because of these attitudes that many users fail to report problems, so Lawnchair is full of inconsistency because of amateur programming errors.  Change this attitude or have continued to be a team developing a badly finished and defective launcher.

**Comment by DanGLVK** [comment] 2019-08-18 16:54
@GabrielMGitHub the other issue is still open, only your issue was closed for being a duplicate and not properly following the issue reporting template, also you have to take into account that lawnchair is a project developed by an extremely small team, mistakes happen, we still have lots of things to solve but many of us are busy and don't have all the time in the world to fix everything

So don't go around criticizing a project which is currently in alpha stage for a reason

**Comment by DanGLVK** [comment] 2019-08-18 17:06
The issue in general is still open, we've just decided to close yours due to it being a duplicate so there's no need to be angry about as we will look into your issue when possible

**Comment by suphon-t** [comment] 2019-08-18 22:46
@GabrielMGitHub 
> The other question was also closed, and my question was reported accordingly, only > being too retarded not to see it.

I’m really sorry, but I can’t see where it says closed on the issue. 
![1930E02C-D9E0-4CBE-9DFC-5AA02C36BA51](https://user-images.githubusercontent.com/8080853/63231325-40aaa280-c244-11e9-953a-d0a605365fab.jpeg)


> Lawnchair is full of inconsistency because of amateur programming errors

This is why the project is open source, so professional programmers like you can easily see and fix the problems instead of complaining. Isn’t that good?

**Comment by DanGLVK** [comment] 2019-08-18 23:10
@GabrielMGitHub pardon for our somewhat rude attitude but we have already told you that the issue is open, please next time you go to report an issue make sure there isn't already an issue exactly like yours, and please follow the issue reporting template, we're deeply sorry if we offended you in any way

**Comment by RokeJulianLockhart** [comment] 2025-10-30 14:37
@DanGLES3, it's not you. The lad has some serious anger problems. [^1] This was a very cruel thread to read: just want to say that you didn't deserve that, at all.

[^1]: [`FedoraQt/MediaWriter/issues/669#issuecomment-3468198718`](https://github.com/FedoraQt/MediaWriter/issues/669#issuecomment-3468198718)
