### ISSUE TITLE
Bug with popup menu in recents

### ISSUE THREAD

**Issue by fordownloads** [Deletescape-Media/Lawnchair#1564] opened 2019-05-21 18:31 UTC
## Description

When you double tap on icon in recents, pop up menu will behave very strange.

## Video
https://drive.google.com/file/d/1tH0lbGmKA9HxfPgy4MvEiBf1Vq66QUDq/view?usp=drivesdk

**Comment by nyancrimew** [comment] 2019-05-23 05:09
I'm able to reproduce.

Probably an upstream bug, let's try to fix and submit upstream.

**Comment by RikKoedoot** [comment] 2021-08-28 15:50
Closing because effort has moved to v11

**Closed as completed by RikKoedoot** 2021-08-28 15:50 UTC
Labels: bug
