### ISSUE TITLE
A RTL Bug in the Hebrew Version

### ISSUE THREAD

**Issue by eyal-sasson** [Deletescape-Media/Lawnchair#1213] opened 2018-04-17 04:38 UTC
## Description

In the Hebrew version, there is a RTL bug, when I do a long press on an app, the shortcut window is showing in the right, and not above the app icon.

## Steps to Reproduce

![screenshot_20180417-073534](https://user-images.githubusercontent.com/37512471/38848879-207514fe-4212-11e8-9752-879ac4167530.png)

## Environment

* Device: Nexus 5X
* Android version: 8.1
* Launcher version: lastest (1.1.0.1872)

**Comment by divadsn** [comment] 2018-04-17 04:38
@eyal100 RTL Support is currently on our list, please be patient :)

**Comment by bsagal** [comment] 2018-06-12 18:53
I think this is a duplicate of #1180

**Comment by yosimor** [comment] 2018-10-04 14:56
Duplicate of #977 as well.

**Closed as completed** 2019-04-07 11:56 UTC
