### ISSUE TITLE
Battery Drain 

### ISSUE THREAD

**Issue by ShadowRedel** [Deletescape-Media/Lawnchair#488] opened 2017-08-11 18:31 UTC
The Launcher uses too much Battery on Nexus 6P Android O Developer build 4
![screenshot_20170811-202603](https://user-images.githubusercontent.com/30420859/29226868-f74f8a3e-7ed3-11e7-8a17-a00ad49dde82.png)

**Comment by intelligentcasanova** [comment] 2017-08-11 19:49
Duplicate of #304.
Please search existing issues before opening a new one.

**Comment by intelligentcasanova** [comment] 2017-08-11 19:49
Duplicate of #305.
Please search existing issues before opening a new one.

**Comment by ShadowRedel** [comment] 2017-08-11 19:55
Men there are like 500 issues, I opening a new one to comment MY issues, if anyone have the same as my, well, more support to the issue

**Comment by intelligentcasanova** [comment] 2017-08-11 20:26
@ShadowRedel, at first I'd like to comment on the disrespectful way you talk to people. Furthermore, your statement about the amount of issues is pure nonsense. Moreover, it just does not work this way; if everybody opens new issues carelessly, the developers won't be able to keep track of the most important issues. Please keep the above in mind if you ever happen to open a new issue.

**Comment by ShadowRedel** [comment] 2017-08-11 20:32
Sorry for my english I trying at best I can but I'm not from UK or USA, I'm new on this of "Development" and oppening issues I'm only try helping, sorry @intelligentcasanova

**Comment by intelligentcasanova** [comment] 2017-08-11 20:42
@ShadowRedel, helping is only appreciated and everybody can learn from each other. This issue is a duplicate so now you, as the issue opener, can close it again.

**Closed as completed** 2017-08-11 20:43 UTC
