### ISSUE TITLE
[BUG] Search on Startpage still displayed after turning off Web Suggestions in Drawer Search

### ISSUE THREAD

**Issue by dave12311** [Deletescape-Media/Lawnchair#4247] opened 2024-04-08 13:57 UTC
### Describe the bug

'Search on Startpage' should not be displayed in Drawer Search if Web Suggestions are disabled under Home Settings > Drawer Search.

### Steps to reproduce

1. Go to Home Settings > Drawer Search
2. Disable 'Web Suggestions'
3. Open the App Drawer and search for anything

### Expected behavior

'Search on Startpage' should not be an option in the App Drawer when Web Suggestions are explicitly disabled

### Device information

- Device: Google Pixel 6
- OS: stock ROM Android version 14
- App version:  14 Beta 2

**Comment by C8opmBM** [comment] 2024-04-09 11:56
They have a partnership with startpage, but this should not be feeding us the web search suggestion if we choose to disable it.
Thanks!

**Comment by naiyerasif** [comment] 2024-04-09 16:47
Duplicate of #4241

**Closed as not planned** 2024-04-10 03:17 UTC
Labels: bug
