### ISSUE TITLE
Search pill becoming hidden after wallpaper change

### ISSUE THREAD

**Issue by halleythomas** [Deletescape-Media/Lawnchair#152] opened 2017-07-07 01:42 UTC
After changing the wallpaper by long pressing on the home page and navigating to Wallpapers and selecting one, the search pill goes away. It will be back if you open the app drawer once and close it.

**Comment by AxiK101** [comment] 2017-07-17 22:18
Indeed

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by RWOne** [comment] 2017-07-28 13:22
I can confirm this behavior as well. Just had it disappear on me and swiped up, when I swiped down the drawer, the pill rendered on refresh.

N6, stock 7.1.1

**Comment by nyancrimew** [comment] 2017-07-28 13:35
duplicate of #27

**Closed** 2017-07-28 13:35 UTC

**Comment by RWOne** [comment] 2017-07-28 13:40
@deletescape , sorry Til, did a search, this one came up top so...
