### ISSUE TITLE
[Feature Request] Enable Folders in App Drawer

### ISSUE THREAD

**Issue by jabia13** [Deletescape-Media/Lawnchair#671] opened 2017-09-04 14:11 UTC
Hi @deletescape, @fonix232 & @paphonb 

I'd like to see us implement the ability to create folders in the app drawer. This would enable better management of the app drawer  and greatly improve productivity. For example, office apps and banking apps can be separately categorized in the app drawer without having to clutter the home screen.

This functionality is similar to what is currently available in Samsung's TouchWiz app drawer (home). My ideal setup would have folders created at the top of the app drawer so the most important apps are easily within reach.

Thanks for all your effort so far, they are greatly appreciated. Please let me know if you'd need any further clarifications.

#FeatureRequest

**Comment by LinuxLlama** [comment] 2017-09-04 15:06
Duplicate of #666

**Comment by jabia13** [comment] 2017-09-04 15:25
Thanks for the cross-reference @treemindr. I found that #666 wasn't properly articulated, hence this. I hope our devs can take this up though

**Comment by guest4711** [comment] 2017-09-04 22:37
See also #362

**Comment by frankh93** [comment] 2017-09-05 04:47
Agree with this request, hope devs bring out this soon

**Comment by nyancrimew** [comment] 2017-09-05 08:29
@jabia13 if you think #666 isn't properly articulated make a comment there with your additions. Duplicate issues only create more work for us and don't help anyone. There is no need to open new issues for existing requests.

**Closed as completed by nyancrimew** 2017-09-05 08:29 UTC

**Comment by jabia13** [comment] 2017-09-05 08:36
Duly noted @deletescape. Will repost there.

Cheers
