### ISSUE TITLE
Individual selection of custom icons

### ISSUE THREAD

**Issue by jay-chorus** [Deletescape-Media/Lawnchair#205] opened 2017-07-15 05:45 UTC
I'm not sure how you could implement this function into the app, but if possible, can you enable the user to choose specific icons from their icon packs for each app...by holding on an app and using the edit function? ... useful for those who want prefer another variant on an app icon and the icon pack supports it.

**Comment by nyancrimew** [comment] 2017-07-15 09:13
duplicate of #25

**Closed as completed by nyancrimew** 2017-07-15 09:13 UTC
