### ISSUE TITLE
Question: Settings backup

### ISSUE THREAD

**Issue by versavius** [Deletescape-Media/Lawnchair#348] opened 2017-07-29 12:28 UTC
At present we can manually export/import our settings which is great.

Does your app allow the settings to be auto backed up to  my Google account so if I wipe.my device and reinstall all my settings would be re-downloaded automatically?

**Comment by AxiK101** [comment] 2017-07-29 19:15
Its only local back, no cloud service supporting

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jacksonhvisuals** [comment] 2017-07-31 02:32
You could set up an autobackup with another app to back up that directory to GDrive...

**Comment by versavius** [comment] 2017-07-31 08:04
Yes I can do that this backup to Google is not a big deal I just thought if it's an easy thing to do it would be a simple at to back everything up without having to do any config

**Comment by intelligentcasanova** [comment] 2017-08-09 18:47
Duplicate of #142

**Closed as completed** 2017-08-10 05:40 UTC
