### ISSUE TITLE
L11 sometimes can't swipe up to homescreen.

### ISSUE THREAD

**Issue by fusk-l** [Deletescape-Media/Lawnchair#2152] opened 2021-05-20 14:26 UTC
So etimes it requires multiple swipes up to return to homescreen.
Sometimes when switching app, screen blinks and  then gets stuck at that app, you'll have to swipe up, and the retry when at the homescreen.
Long swipe up from homescreen works fine.

I have tried uninstalling and reinstalling lawnchair, lawnfeed and quickswitch. Issues only present with L11.
1+6, oos 11.

**Comment by Atrate** [comment] 2021-05-20 15:30
Sounds like it's caused by crashes, no?

**Comment by fusk-l** [comment] 2021-05-20 15:31
No crashes appear. But not saying that isn't the case, it's just not obvious.

**Comment by RikKoedoot** [comment] 2021-08-27 09:58
Does it still occur on alpha 6?

**Comment by suphon-t** [comment] 2021-08-27 10:44
This is fixed in alpha 6

**Closed as completed by suphon-t** 2021-08-27 10:44 UTC
