### ISSUE TITLE
[BUG] NullPointerException when moving an icon in app drawer

### ISSUE THREAD

**Issue by compscidoggo** [Deletescape-Media/Lawnchair#3063] opened 2022-10-28 23:53 UTC
### Describe the bug

Lawnchair crashes with a NullPointerException after attempting to move it (to remove or uninstall it).

### Steps to reproduce

1. Swipe up to open app drawer
2. Press and hold an icon to move it
3. Move the icon around
4. Crash

### Expected behavior

The app should be free to move around when you drag.

### Device information

- Device: Samsung Galaxy S22 Ultra
- OS: Android 12 One UI 4.1
- App version: 12.1.0 Alpha 4

### Additional context

[Lawnchair_bug_report_Oct_28_2022_72336_PM.txt](https://github.com/LawnchairLauncher/lawnchair/files/9892467/Lawnchair_bug_report_Oct_28_2022_72336_PM.txt)

**Comment by Goooler** [comment] 2022-10-31 04:53
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.ViewGroup.getParent()' on a null object reference
	at com.android.launcher3.Workspace.onDragStart(Workspace.java:3)
	at com.android.launcher3.dragndrop.DragController.callOnDragStart(DragController.java:8)
	at com.android.launcher3.dragndrop.DragController.handleMoveEvent(DragController.java:14)
	at com.android.launcher3.dragndrop.DragController.onDriverDragMove(DragController.java:2)
	at com.android.launcher3.dragndrop.DragDriver$InternalDragDriver.onTouchEvent(DragDriver.java:6)
	at com.android.launcher3.dragndrop.DragController.onControllerTouchEvent(Unknown Source:4)
	at com.android.launcher3.views.BaseDragLayer.onTouchEvent(BaseDragLayer.java:6)
	at android.view.View.dispatchTouchEvent(View.java:15076)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3917)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3581)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:13)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:2)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3923)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3597)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1016)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1962)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4265)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:6)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:974)
	at android.view.View.dispatchPointerEvent(View.java:15335)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7820)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7593)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6927)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6984)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6950)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7148)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6958)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7205)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6931)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6984)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6950)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6958)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6931)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10422)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10270)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10226)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10554)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:239)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:10502)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:10643)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by Goooler** [comment] 2023-01-20 06:24
Duplicate of #3143.

**Closed as completed** 2023-01-20 09:04 UTC
Labels: bug
