### ISSUE TITLE
[BUG] Google Feed not working in Lawnchair 14 Beta 2

### ISSUE THREAD

**Issue by AdityaMittal-Fintech** [Deletescape-Media/Lawnchair#4239] opened 2024-04-07 03:51 UTC
### Describe the bug

In home screen setting of Lawnchair 14 Beta 2 even after enabling the feed, with and without lawnfeed version 3 installed, the feed doesn't show up when swiping right on the device. 

I'm using Samsung s24 ultra. 

### Steps to reproduce

1. Go to Home settings
2. Click on Home Screen
3. Scroll down to Show Feed and enable it
4. Come back to home page and swipe right

Tried these steps with and without lawnfeed version 3

### Expected behavior

It should show the Google Feed. 

### Device information

- Device: Samsung S24 Ultra 
- OS: One UI version 6.1
- App version: 14 Beta 2

**Comment by st0neh** [comment] 2024-04-07 08:16
For me it works fine until I access the "Feed Provider" menu, then it breaks.

**Comment by Pyntux** [comment] 2024-04-07 11:43
In debug version works fine, so I think this is solved...

**Comment by jhawkins002** [comment] 2024-04-07 16:43
> In debug version works fine, so I think this is solved...

Works on debug but not release. I believe it is related to differences in how the Google Feed apis handle debug-level connections vs others. Basically IIRC it's more permissive under debug.

**Comment by jhawkins002** [comment] 2024-04-07 16:46
Duplicate of https://github.com/LawnchairLauncher/lawnchair/issues/4201

**Closed as completed** 2024-12-16 07:42 UTC
Labels: bug
