### ISSUE TITLE
Ho to create folder on app drawer?

### ISSUE THREAD

**Issue by sombresu** [Deletescape-Media/Lawnchair#2781] opened 2022-07-20 06:21 UTC
I've searched google found nothing. There's no categorization option anywhere. 

Lawnchair 12.10
Android 11
Miui 12.5

**Comment by yasanglass** [comment] 2022-07-20 07:19
It's not possible on the current version.

**Comment by blogmangit** [comment] 2022-08-12 14:31
please lawnchair team add this feature its been a while we really need this feature.

**Comment by Amorphous404** [comment] 2022-08-21 02:29
Duplicate of #2471

**Comment by SuperDragonXD** [comment] 2022-08-21 04:05
Actually mark as a duplicate of #2471

**Closed as completed by SuperDragonXD** 2022-08-21 04:05 UTC
