### ISSUE TITLE
[BUG] Duplicate shortcuts when dragging into a folder

### ISSUE THREAD

**Issue by Terrance** [Deletescape-Media/Lawnchair#3020] opened 2022-10-12 21:57 UTC
### Describe the bug

When dragging an app from the app drawer into a docked folder as a shortcut, a duplicate shortcut is dumped on the main home screen.  Removing one or the other will cause both to disappear, but they otherwise coexist (and can both be moved independently in and out of folders).  If the app is dragged from the drawer to an empty space on the dock first, it doesn't duplicate.

I've encountered this before with a past installation of Lawnchair, though I can no longer reproduce a day and a reboot later, nor can I reproduce it on a clean install, so I'm not entirely sure what conditions are required to trigger it.

### Steps to reproduce

1. Create a folder in the dock.
2. Drag an app from the drawer into the folder.

### Expected behavior

The new app shortcut ends up in the folder.  (It does, but a second shortcut appears on the current home screen, positioned roughly where the app was originally dragged from.)

I did also manage to trigger a crash interacting with one of these duplicate shortcuts (log at the end of this post) -- after Lawnchair restarted, both copies of the misbehaving shortcut were absent, presumably as the state was last saved before its addition.

### Device information

- Device: OnePlus Nord CE
- OS: OxygenOS 12.1 (Android 12)
- App version: 12.1.0 Alpha 4

### Additional context

<details>
<summary>Log file</summary>

```
Lawnchair bug report 12 Oct 2022 08:57:05
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: OnePlus
build.device: OnePlusNordCE
build.display: EB2103_11_C.07
build.fingerprint: OnePlus/OnePlusNordCE_EEA/OnePlusNordCE:12/RKQ1.211119.001/R.GDPR.202209162338:user/release-keys
build.hardware: qcom
build.id: RKQ1.211119.001
build.manufacturer: OnePlus
build.model: EB2103
build.product: OnePlusNordCE_EEA
build.type: user
version.codename: REL
version.incremental: R.GDPR.202209162338
version.release: 12
version.sdk_int: 31
display.density_dpi: 480
isRecentsEnabled: false

error: Uncaught exception

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.android.launcher3.folder.FolderAnimationManager.getAnimator(FolderAnimationManager.java:12)
	at com.android.launcher3.folder.Folder.animateClosed(Folder.java:5)
	at com.android.launcher3.folder.Folder.handleClose(Folder.java:8)
	at com.android.launcher3.AbstractFloatingView.close(AbstractFloatingView.java:2)
	at com.android.launcher3.folder.Folder.completeDragExit(Folder.java:2)
	at com.android.launcher3.folder.Folder.onDropCompleted(Folder.java:18)
	at com.android.launcher3.dragndrop.DragController.dispatchDropComplete(DragController.java:3)
	at com.android.launcher3.dragndrop.DragController.drop(DragController.java:16)
	at com.android.launcher3.dragndrop.DragController.onDriverDragEnd(DragController.java:2)
	at com.android.launcher3.dragndrop.DragDriver$InternalDragDriver.onTouchEvent(DragDriver.java:12)
	at com.android.launcher3.dragndrop.DragController.onControllerTouchEvent(Unknown Source:4)
	at com.android.launcher3.views.BaseDragLayer.onTouchEvent(BaseDragLayer.java:6)
	at android.view.View.dispatchTouchEvent(View.java:14632)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3163)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:13)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:2)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:573)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1911)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4256)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:6)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
	at android.view.View.dispatchPointerEvent(View.java:14899)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6755)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6526)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5995)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6057)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6018)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6192)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6026)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6249)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5999)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6057)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6018)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6026)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5999)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9034)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8985)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8941)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9177)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:266)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loopOnce(Looper.java:179)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```
</details>

**Comment by ciphero** [comment] 2022-10-19 09:02
This bug is not only seen on dock folders but all folders.
Seems to be a duplicate of https://github.com/LawnchairLauncher/lawnchair/issues/2784

**Comment by yasanglass** [comment] 2022-10-19 09:29
Closing as its a duplicate of #2784

**Closed as not planned by yasanglass** 2022-10-19 09:29 UTC
Labels: bug

**Comment by Terrance** [comment] 2022-10-19 09:34
Sorry, yes, that appears to be the same issue.  Just to clarify, it affects subsequent drags into the folder too, not just the initial folder creation (i.e. every icon dropped into the folder gains a duplicate on the home screen).
