### ISSUE TITLE
App shortcuts can't bei created

### ISSUE THREAD

**Issue by Xyolyp** [Deletescape-Media/Lawnchair#1086] opened 2017-12-18 07:31 UTC
When I press on add to Home screen in Google Chrome nothing happens.

## Environment
* Device: Nexus 6P
* Android version: 8.1
* Launcher version: latest Google Play Download
* Rom: Stock

**Comment by divadsn** [comment] 2017-12-18 07:33
Duplicate of #942, use the search function please!

**Closed as completed** 2017-12-18 07:33 UTC
