### ISSUE TITLE
Please add an option to show hidden apps in search results

### ISSUE THREAD

**Issue by jahirfiquitiva** [Deletescape-Media/Lawnchair#497] opened 2017-08-12 14:27 UTC
Even when I hide apps, I want to access them every now and then. It would be great to have an option like this. Basically how it works on Nova.
Thanks

**Comment by intelligentcasanova** [comment] 2017-08-12 15:23
Duplicate of #304.
Please close this issue.

**Closed as completed** 2017-08-12 16:40 UTC
