### ISSUE TITLE
App drawer search looks broken and pixelated

### ISSUE THREAD

**Issue by bbq912** [Deletescape-Media/Lawnchair#1568] opened 2019-05-26 17:50 UTC
![Screenshot_20190526-200733](https://user-images.githubusercontent.com/35496217/58385260-1b681880-7ff6-11e9-9c1d-9afb6294c44f.png)

## Environment

* Device: Xiaomi Redmi Note 5 (Whyred)
* Android version: 9.0
* Launcher version: alpha-2078
* Rom: Pixel Experience

**Comment by nyancrimew** [comment] 2019-05-27 06:52
Which DPI/Smallest width is your phone set to? This bug is incredibly hard to reproduce and I have so far failed to do so on like 5 devices.

**Comment by bbq912** [comment] 2019-05-27 08:47
My DPI is 440

Update: Excuse me, I just looked up my smallest width in developer options and it says 392, so I changed it to 400 and everything is alright now

**Comment by LuminarySage** [comment] 2019-06-07 03:44
@bbq912 If it's resolved then you should close the issue

**Comment by RikKoedoot** [comment] 2021-08-28 15:50
Closing because effort has moved to v11

**Closed as completed by RikKoedoot** 2021-08-28 15:50 UTC
Labels: bug, enhancement, help wanted
