### ISSUE TITLE
Notification bubbles out of screen edges

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#438] opened 2017-08-08 09:13 UTC
On costume column settings or screen dpis there is this behavior of bubbles. If i recall it right, costume launchers such as Nova & Action, gave a solition to this problem by moving bubbles inside the screen margins. Is it possible to make it work on Lawnchair too? Thanks
![](http://i.imgur.com/265kkqL.jpg)

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment] 2017-08-08 09:28
Duplicate of #212

**Closed as completed** 2017-08-08 10:38 UTC
