### ISSUE TITLE
Make a release of the current version as-is

### ISSUE THREAD

**Issue by ThatOneCalculator** [Deletescape-Media/Lawnchair#3739] opened 2023-11-17 23:45 UTC
### Describe the feature

An official release APK of the current development version.

### Why would it be useful to add?

It's been over a year since the last release APK for Lawnchair. While the current 13 dev version isn't perfect, as the project's future is uncertain, making a release APK would at least let people use Lawnchair with all the new features, fixes, etc added in the last year without having to use the laggy debug version. 

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

N/A

**Comment by MrSluffy** [comment] 2023-11-18 01:50
Thanks for opening an issue,  In 12.1-dev has a bug #2820 which will be resolve in #3728. 

If you faced a laggy in 13-dev it will much appreciated if you send a logs,screen record so we can reproduce it and will do the best we can to try to fix it

**Comment by ThatOneCalculator** [comment] 2023-11-18 03:28
I don't think the lag is caused by a particular issue, rather, it's inherently slower than a release build due to attaching a debugger.

**Comment by ThatOneCalculator** [comment] 2023-11-20 20:55
Now that #3728 has been merged, what does the timeline look like for this?

**Comment by bill-mcgonigle** [comment] 2023-11-24 02:00
Good idea - this would help with bugs filed against the current release being marked as outdated. It's totally understandable yet also not ideal for an optimum development cycle.  More releases, more testers, more useful bug reports, ad. infinitum.

**Comment by ThatOneCalculator** [comment] 2023-12-12 18:29
It's been a month since, any update on this? I'm currently using https://github.com/LawnchairLauncher/lawnchair/commit/0ea58771789d0cb9221e8addf5e335c2d797e48c with no problems, it'd be great to have more people be able to use this.

**Comment by yasanglass** [comment] 2023-12-12 18:51
There are a few blockers otherwise it would have been done today. I prefer not to give ETAs but we are working on it.

**Comment by ThatOneCalculator** [comment] 2023-12-18 20:51
Given Lawnchair rebased to Launcher3 14, would the upcoming release be based on 13-dev or 14-dev?

**Comment by yasanglass** [comment] 2023-12-18 21:38
It would be released as open beta so it will be the latest version. With the help of Play Store analytics we can fix the major bugs much easier.

**Comment by Goooler** [comment] 2023-12-30 19:41
Users who want to try releases can consider using my fork, check https://github.com/Goooler/LawnchairRelease/releases

**Comment by heschy2** [comment] 2024-02-08 17:12
Also, since the newest Version has the Startpage-Searchengine and explicitly claims that it helps Lawnchair when you search with SP, it would help the ptoject to release this version, if morr people see this, than more people will do it (obviously)

**Comment by yasanglass** [comment] 2024-02-09 19:09
We do want to release a version as soon as possible but all members of the Core Lawnchair team are very busy and cannot invest much time on Lawnchair currently. Also, we are having some trouble with Google which originally delayed the release. 

This is a high-priority task & we are trying to publish a version as soon as possible.

**Comment by Americapax** [comment] 2024-02-27 16:28
I just use the Gooler version:

https://github.com/Goooler/LawnchairRelease

**Comment by heschy2** [comment] 2024-03-06 11:19
Yes me too, however it is impossible to use the Accessability Servive a.o. the Notification Access: Android says i cannot do this... for my own security (actually nice it does that, I never saw these pupoups before...), so this is (obviously) not a permanent solution. But they are working on releasing it, so I'll just wait.

**Comment by WindowsTAS** [comment] 2024-03-09 07:15
What about adding a bot that compiles the dev releases in GitHub Actions weekly (or monthly) just like Goooler version?

**Comment by SuperDragonXD** [comment] 2024-03-09 08:26
Just wanted to give you guys a quick update.

We’re getting closer to the release of Lawnchair 14, and we only need to do the following:

- Finish the design refresh of Lawnchair's Settings UI (by me);
- Implement the live information feature for delegating announcements to users (by Yasan), and;
- Create PR announcements and blog posts.

However, due to some unexpected circumstances, I'll be unable to work on these features until a few days or weeks from now. Yasan is also busy dealing with other matters. On top of that, MrSluffy is currently merging a new A14 branch from AOSP, which contains many conflicts.

Alongside that, we originally intended to release Lawnchair 14 alongside a new Lawnicons version. However, with what I said above, we cancelled our intended plan.

As a result, we may need to postpone the release by a few more weeks. Apologies for any inconvenience this may cause.

**Comment by blackma9ick** [comment] 2024-03-16 21:00
Hi.

No worries, things take time to polish, and we all have other things outside of this in life.

I'm here because the latest pre-release (that will soon be superseded!) still has an ancient issue (#2888) with excessive battery drain.

I'm planning to test a build from latest commit, and see if there is any improvement in battery usage. 

After Lawnchair 14 eventually gets released, perhaps the project should start providing more regular builds, whether stable or unstable, ~~via CI/CD or other~~ ([there is already CI](https://github.com/LawnchairLauncher/lawnchair/actions/workflows/ci.yml), although there are only debug builds), just as some others have suggested.

**Comment by Goooler** [comment] 2024-04-01 04:03
You can try nightly builds at https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly

**Comment by ThatOneCalculator** [comment] 2024-04-01 16:43
Correct me if I'm wrong, but those are still the debug builds, yeah?

**Comment by 88572** [comment] 2024-04-01 20:33
Yes, these are still the debug builds.

**Comment by SuperDragonXD** [comment] 2024-04-03 10:29
Check GitHub releases.

**Closed as completed by SuperDragonXD** 2024-04-03 10:29 UTC
Labels: enhancement, feature-request
