### ISSUE TITLE
 Include hidden apps in searches within the app drawer

### ISSUE THREAD

**Issue by macuduranti** [Deletescape-Media/Lawnchair#388] opened 2017-08-03 03:16 UTC
Hey wouldn't it be a good idea to include hidden apps results in searches from the app drawer?
I think it would be a great feature, and could be optional to activate in the settings

**Comment by suphon-t** [comment] 2017-08-06 04:07
Duplicate of #304

**Closed as completed by suphon-t** 2017-08-06 04:07 UTC
