### ISSUE TITLE
Please fix this widget color

### ISSUE THREAD

**Issue by ArmanKir-yan25** [Deletescape-Media/Lawnchair#506] opened 2017-08-12 22:09 UTC
![screenshot_20170813-020747](https://user-images.githubusercontent.com/30963247/29244579-59804ab0-7fcc-11e7-96e1-f08bfbbc1596.jpeg)

It's ugly

**Comment by suphon-t** [comment] 2017-08-13 03:25
Duplicate of #466

**Closed as completed by suphon-t** 2017-08-13 03:25 UTC
