### ISSUE TITLE
Accent Color Presets Wrong Color Bug

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#2283] opened 2021-10-29 05:21 UTC
Yellow and Orange color presets are not proper color. They're different shades of brown.

**Comment by RikKoedoot** [comment] 2022-01-12 18:47
closing as this does not seem to be the case anymore

**Closed as completed by RikKoedoot** 2022-01-12 18:47 UTC

**Comment by ghost** [comment] 2022-01-12 19:00
Are you talking about coming release? Current alpha still has it.

**Comment by RikKoedoot** [comment] 2022-01-12 19:07
Could you show a screenshot of it then? As for me it is not happening in the current development build

**Comment by ghost** [comment] 2022-01-12 19:20
![Screenshot_20220112-141705_Lawnchair](https://user-images.githubusercontent.com/92182796/149207400-23322dad-caa4-4e53-82ed-48fb6cb334e5.png)
![Screenshot_20220112-141646_Lawnchair](https://user-images.githubusercontent.com/92182796/149207412-47a13d68-56d4-4c72-b395-420ac5b39443.png)

**Comment by ghost** [comment] 2022-01-12 19:21
They're all different shades from shown color.

**Comment by RikKoedoot** [comment] 2022-01-12 19:29
That's intended behavior I guess as the Monet theme engine would do the same, it's so that it's still legible. If you go to dark theme you'll see that it is yellow and orange

**Comment by ghost** [comment] 2022-01-12 19:37
Ok, it's understood. I want the selected colors on light theme. Is what it is but still great work.
