### ISSUE TITLE
Double tap > screen off

### ISSUE THREAD

**Issue by xmiseggs** [Deletescape-Media/Lawnchair#143] opened 2017-07-06 06:20 UTC
Please include turning the screen off when double tap

**Comment by bappa555** [comment] 2017-07-07 16:29
First, thanks for building this app. This is really cool, it will be even better if the feature to lock screen on double tap can be enabled.

**Comment by Trak-X** [comment] 2017-07-08 20:21
It has been already requested. It should be here soon.

**Comment by deletescape** [comment] 2017-07-08 22:21
duplicate of #40

**Closed by deletescape** 2017-07-08 22:21 UTC
