### ISSUE TITLE
Launcher does not have recent apps bar

### ISSUE THREAD

**Issue by AndersonARS** [Deletescape-Media/Lawnchair#449] opened 2017-08-08 17:42 UTC
Enable the recent apps bar. please. I really need this function. You change everything but do not put the bar. damn it. It does not ative a barra de apps recentes. por favor. eu preciso muito dessa função . você muda tudo mas não coloca a barra. caramba. não custa nadaEnable the recent apps bar. please. I really need this function. You change everything but do not put the bar. damn it. It does not cost anything to insert this . Thank you if you understand me.

**Comment by AndersonARS** [comment] 2017-08-08 17:45
![screenshot_20170808-141149](https://user-images.githubusercontent.com/30668080/29086140-eaa58484-7c47-11e7-9df9-361d393ad7ca.png)
This is an image of the original launcher pixel of Android 8.0, where it has the recent apps bar. Why do not you put the same bar in your launcher ?! What's wrong with her not having it yet ?!

**Comment by ravithoria** [comment] 2017-08-08 18:06
Same here missing recent bar

**Comment by nyancrimew** [comment] 2017-08-08 18:09
This is not yet implemeted

**Comment by AxiK101** [comment] 2017-08-08 18:11
@deletescape 
Do you have a schedule plan fir when ti expect it? It's quite an old request..

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suphon-t** [comment] 2017-08-08 23:41
Duplicate of #242

**Closed as completed by suphon-t** 2017-08-08 23:41 UTC

**Comment by nyancrimew** [comment] 2017-08-09 04:52
@AxiK101 1. Stop being a dick please

2. We have over 100 fcking issues and some of them are way more important thant this shit

3. We do this for free and for fun, and we could just not implement this feature at all if we don't feel like it.
