### ISSUE TITLE
Request: per icon themeing for missing pixel icons

### ISSUE THREAD

**Issue by 14142000** [Deletescape-Media/Lawnchair#155] opened 2017-07-07 06:20 UTC
i'd love a per icon theming system where you could theme icons that aren't made circular with the pixel icons.  Or some that are but don't get displayed as such by third party launcher like the camera app.  Would work well in the rename dialogue you can tap on the icon to select a new one from a icon pack,

**Comment by deletescape** [comment] 2017-07-07 06:34
Duplicate of #25

**Closed by deletescape** 2017-07-07 06:34 UTC
