### ISSUE TITLE
[BUG] Apps in app drawer search prompt to open the Play Store if icon isn't clicked

### ISSUE THREAD

**Issue by fesdonomist** [Deletescape-Media/Lawnchair#3854] opened 2023-12-14 11:22 UTC
### Describe the bug

When I search for an individual app in the app drawer, and it is the only one that appears, if I click anywhere but the app icon on the left I am prompted to open the Play Store or F-Droid to open the app. 

### Steps to reproduce

1. Go to the app drawer.
2. Search for an individual app, make sure that it is the only one shown, with icon on the left and text in the center.
3. Click on the text, instead of the icon.
4. See prompt to open the Play Store.
5. Click on the icon, instead of the text.
6. App opens as expected.

### Expected behavior

I expect the app that I searched for to open normally if anywhere on the button area is clicked, rather than being prompted to "Open with Play Store".

### Screenshots

https://github.com/LawnchairLauncher/lawnchair/assets/71878148/e2cab59f-116f-4b22-ae83-5a9580085e48

### Device information

- Device: Motorola Edge 20 Pro
- OS: LineageOS 20 w/ Magisk 25.2
- App version: Lawnchair (Debug) 13 Dev (`#2492`)

### Additional context

I'm using QuickSwitch Magisk module on Android 13. I previously had some trouble with app icons applying to certain apps with a Lawnicons dev build while I was contributing to that.

**Comment by pacjo** [comment] 2023-12-14 15:24
Duplicate of #3740 and #3817, also fixed by #3785.

**Closed as completed** 2023-12-14 15:26 UTC
Labels: bug
