### ISSUE TITLE
Persistent Searchbar

### ISSUE THREAD

**Issue by one17dev** [Deletescape-Media/Lawnchair#246] opened 2017-07-18 23:09 UTC
Title says it all.
 Great launcher, my daily driver. Thanks!

_Sent from my Android XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment] 2017-08-09 18:34
Duplicate of #58

**Closed as completed** 2017-08-10 05:39 UTC
