### ISSUE TITLE
[FEATURE] Change default Home Screen

### ISSUE THREAD

**Issue by Dogway** [Deletescape-Media/Lawnchair#3127] opened 2022-11-24 18:59 UTC
### Describe the feature

Option to set the default Home Screen to another panel on the right when you press the Home button in the NavBar.

### Why would it be useful to add?

By default the Home Screen is set to the left most panel, narrowing the possible panels (and hence apps) you can access with one finger slide from 2 to 1. Basically removing non-sense design (the default feed is only an income channel for the companies).

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

There was a precedent ticket #1245 almost 5 years back, but many things have changed, including many non Pixel style features being included.

Thanks.

**Comment by Goooler** [comment] 2022-11-25 02:36
Related to #2889.

**Comment by redthing1** [comment] 2023-01-07 19:40
I want this too

**Comment by Goooler** [comment] 2023-01-21 14:08
Yeah, this is a necessary feature.

**Comment by Goooler** [comment] 2023-01-26 05:44
Duplicate of #2683

**Comment by Goooler** [comment] 2023-01-26 05:48
Will track this issue there.

**Closed as not planned by Goooler** 2023-01-26 05:48 UTC
Labels: enhancement, feature-request
