### ISSUE TITLE
Mention GitHub on Google Play

### ISSUE THREAD

**Issue by jidanni** [Deletescape-Media/Lawnchair#2439] opened 2022-01-26 21:25 UTC
https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah  should mention somewhere that the app is open source, and mention its GitHub address.

**Comment by SuperDragonXD** [comment] 2022-08-12 16:27
Late reply, but please don't make duplicate issues (in this case, a duplicate of #2438). Instead, provide all info in one issue if you can.

**Closed as completed by SuperDragonXD** 2022-08-12 16:27 UTC
