### ISSUE TITLE
[BUG] Horizontal Padding is broken

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#4527] opened 2024-06-29 06:37 UTC
### Describe the bug

App drawer Horizontal Padding is broken

### Steps to reproduce

App drawer > Horizontal padding

### Expected behavior

Work as intended.

### Device information

- Device: Samsung F22
- OS: Android 13 One UI 5.1
- App version: Latest debug build 1046

**Comment by Unofficial-Life** [comment] 2024-06-29 16:44
I think its mainly due to this commit 930d0e6

devs please take a look once

**Comment by harmit03** [comment] 2024-06-30 09:17
Maybe there is something hin this file 

...lawnchair/src/app/lawnchair/allapps/views/SearchResultRightLeftIcon.kt

I am not sure but just seems like it.

**Comment by harmit03** [comment] 2024-07-02 07:26
Duplicate of #4513

**Closed as not planned** 2024-07-03 07:29 UTC
Labels: bug
