### ISSUE TITLE
Lawnchair consume a lot of battery

### ISSUE THREAD

**Issue by R3Cyrax** [Deletescape-Media/Lawnchair#463] opened 2017-08-09 10:42 UTC
Hi,
The app consume a lot of battery http://i.imgur.com/PIdQC0W.png
I have a Nexus 6P running Android O Developer Preview 4.

**Comment by nyancrimew** [comment] 2017-08-09 10:44
Duplicate of #305 This is only an issue in the battery metering of DP4, Lawnchair doesn't actually have such an impact on battery.

**Closed as completed by nyancrimew** 2017-08-09 10:44 UTC
