### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Oxzinxd** [Deletescape-Media/Lawnchair#2895] opened 2022-08-29 16:56 UTC
### Describe the bug

When i put a third-party widget its crashes not kwgt widgets, it's happens only in the third-party apps widgets

### Expected behavior

When i put a third-party widget its crashes not kwgt widgets, it's happens only in the third-party apps widgets

### Screenshots

It's don't have a screen shot 

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]
Device redmi note 7
OS miui 12.5
App version latest bulid 12.1.0 alpha 4

### Additional context

[Lawnchair bug report Aug 29, 2022 101541 PM.txt](https://github.com/LawnchairLauncher/lawnchair/files/9446424/Lawnchair.bug.report.Aug.29.2022.101541.PM.txt)

**Comment by SuperDragonXD** [comment] 2022-09-07 11:43
Duplicate of #2820

**Closed as not planned by SuperDragonXD** 2022-09-07 11:43 UTC
Labels: bug
