### ISSUE TITLE
Shortcuts out of screen on LG G6 qhd 18:9 stock 7.0

### ISSUE THREAD

**Issue by stefanvanruiten** [Deletescape-Media/Lawnchair#633] opened 2017-08-30 11:02 UTC
On my default LG G6 with unrooted Android 7.0 and default dpi my app shortcuts fall off the screen on the left side.

**Comment by suphon-t** [comment] 2017-08-30 15:48
Duplicate of #212

**Closed as completed by suphon-t** 2017-08-30 15:48 UTC
