### ISSUE TITLE
[Request] Reorder Home Screen pages

### ISSUE THREAD

**Issue by ascworl** [Deletescape-Media/Lawnchair#2228] opened 2021-09-09 22:53 UTC
We should be able to change the default home screen from being the one on the far left.
And we should be able to reorder Home Screen pages by dragging and dropping.
https://github.com/otakuhqz/Omega/issues/116

Will donate to get these features

Also looking to get multiple dock rows like how Microsoft Launcher works. Dragging up from the dock displays 1 to 2 more rows

And the ability to back up and restore locally

**Comment by masscream** [comment] 2022-08-15 20:25
It would have been awesome to add this feature.

**Comment by Amorphous404** [comment] 2022-08-23 05:28
Duplicate of #1846

**Comment by SuperDragonXD** [comment] 2022-08-23 06:16
Not really a duplicate, but is superseded by #2683. Also features won't be added even if you donated something to Lawnchair.

**Closed as completed by SuperDragonXD** 2022-08-23 06:16 UTC
