### ISSUE TITLE
At a Glance widget doesn't show battery status, even when nothing else is shown

### ISSUE THREAD

**Issue by Freeplayg** [Deletescape-Media/Lawnchair#2146] opened 2021-05-12 11:51 UTC
![Screenshot_20210512-072646_Lawnchair](https://user-images.githubusercontent.com/40742947/117970500-ba2ad400-b2f6-11eb-9026-97bea8919364.jpg)

I have the Android topbar hidden, so it would be nice if the battery status always showed.

Phone: Samsung J7 Star
Android Version: 9
One UI Version: 1.1

**Comment by RikKoedoot** [comment] 2021-05-16 16:50
This is expected behavior, it only shows up when charging

**Comment by Freeplayg** [comment] 2021-05-16 16:59
Wouldn't it make sense to always show though? Or at least have an option to always show it.

**Comment by RikKoedoot** [comment] 2021-05-16 17:31
If you have nothing else enabled it does make sense, but if you have other sources below battery and if battery always shows those sources under battery would never show, this is why we did it this way

**Comment by ghost** [comment] 2021-06-06 03:51
Well at least you have the percentage of the status bar 🤷🏾‍♂️ they're just tryna make the At a Glance widget a replica, if I say, of the Pixel ones.

**Comment by RikKoedoot** [comment] 2021-08-27 10:00
Closing because effort has been moved to v11

**Closed as completed by RikKoedoot** 2021-08-27 10:00 UTC
