### ISSUE TITLE
App suggestions

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#242] opened 2017-07-18 15:23 UTC
Why this isn't icluded in the settings menu?

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nyancrimew** [comment] 2017-07-18 15:32
Because it is not implemented yet.

**Comment by AxiK101** [comment] 2017-07-18 15:37
@deletescape Oh i see, if it's in the "to do" list then lets wait for it👍

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by intelligentcasanova** [comment] 2017-08-09 18:33
Duplicate of #62

**Closed as completed** 2017-08-10 05:39 UTC
Labels: feature-request
