### ISSUE TITLE
[BUG] homescreen grid changes horizontal padding for dock 

### ISSUE THREAD

**Issue by harsha20599** [Deletescape-Media/Lawnchair#4560] opened 2024-07-12 04:26 UTC
### Describe the bug

I have changed to homescreen grid to 10x10 and it reduces the horizontal padding for the dock with 4 icons. 

Happening on both latest nightly and beta builds
![Screenshot_20240712-094454](https://github.com/user-attachments/assets/00ffb619-d9e3-43e8-a18a-4b9ad593e5ef)
![Screenshot_20240712-094421](https://github.com/user-attachments/assets/03b6d91e-d3b2-4bb9-8f82-c06b5f4e1716)

### Steps to reproduce

Increase homescreen grid to maximum 

### Expected behavior

I want the dock to have it's properties and should not get changed with homescreen.

### Device information

- Device: Nothing phone 2 (pong)
- OS: Superior OS 14
- App version: 14 Nightly #1078

### Additional context

I used lawnchair because of it's well defined spacing and smoothness. 

I am increasing homescreen grid due to have good widget size control but don't want to mess up my dock.

**Comment by MrSluffy** [comment] 2024-07-25 01:57
This is not a bug, it supposed to be this, this should be feature request rather than marked as bug

**Closed as completed** 2024-12-15 02:16 UTC
Labels: bug
