### ISSUE TITLE
[BUG] crash when adding widgets

### ISSUE THREAD

**Issue by HyroGoth** [Deletescape-Media/Lawnchair#2919] opened 2022-09-08 06:12 UTC
### Describe the bug

Trying to add samsung widgets makes lawnchair to crash.

### Steps to reproduce

1. Click and hold on initial screen
2. Click on 'widgets'
3. Scroll down to 'Samsung Notes'
4.try to add 'Note shortcut'
5. See error

### Expected behavior

Open the widget settings menu then wen it's done go back to the initial screen ann nothing wrong happen

### Device information

- Device: Samsung A75 5G SM-A736B/DS
- OS: stock ROM Android version 12.0
- App version: 12.1.0 Alpha 4

### Additional context

![Screenshot_20220908-030445_Lawnchair](https://user-images.githubusercontent.com/113087198/189047579-58cd1d5f-9b05-403c-b2b4-d76aaa117059.png)

**Comment by saulhdev** [comment] 2022-09-09 02:51
Duplicate of #2820

**Comment by SuperDragonXD** [comment] 2022-09-09 03:04
Actually mark as a... Duplicate of #2820

**Closed as not planned by SuperDragonXD** 2022-09-09 03:04 UTC
Labels: bug
