### ISSUE TITLE
Dark folders revert to light

### ISSUE THREAD

**Issue by AxiK101** [Deletescape-Media/Lawnchair#384] opened 2017-08-02 19:23 UTC
It's a bug in latest versions, can you fix it plz?

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AxiK101** [comment] 2017-08-04 22:20
Here what i mean:

![](http://i.imgur.com/rrNpABu.png)

![](http://i.imgur.com/XNC8gBB.png)

![](http://i.imgur.com/sQLViSP.png)


_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by suphon-t** [comment] 2017-08-05 15:28
Duplicate of #340 

But why are you creating two issues for the same bug?

**Closed as completed by suphon-t** 2017-08-05 15:28 UTC
