### ISSUE TITLE
[Feature Request] Subgrid Positioning

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [Deletescape-Media/Lawnchair#2750] opened 2022-07-04 18:38 UTC
I love the subgrid positioning feature found in Nova Launcher and Microsoft Launcher and would love for it to be implemented into Lawnchair.

**Comment by SuperDragonXD** [comment] 2022-08-09 05:11
Duplicate of #1893

**Closed as completed by SuperDragonXD** 2022-08-09 05:11 UTC
