### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by NoireFHC** [Deletescape-Media/Lawnchair#267] opened 2017-07-21 15:22 UTC
I am using tablet devices,I can't use auto rotate in this launcher

**Comment by fonix232** [comment] 2017-07-21 15:33
Auto rotate and tablets are generally not supported (yet), since we don't have layouts for them.

**Comment by suphon-t** [comment] 2017-07-21 16:00
Duplicate of #34

**Closed as completed by suphon-t** 2017-07-21 16:00 UTC
