### ISSUE TITLE
Can't place some (Huawei) 4x3 widgets

### ISSUE THREAD

**Issue by EliasSchriefer** [Deletescape-Media/Lawnchair#1195] opened 2018-03-29 08:23 UTC
## Description

I'm not able to place some 4x3 widgets of my Huawei system apps (tested with Notes and Email) on the home screen, even on a new empty page. I did not change the rows and columns.

## Expected Behavior

The widgets should behave as normal widgets.

## Actual Behavior

Toast: „No more room on this page.“

## Steps to Reproduce

1. Search for an 4x3 widget (for example the Notes or Email widget)
2. Try to place it on the home screen (existing or new page)

## Environment

* Device: Huawei P8 Lite (ALE-L21)
* Android version: 6.0
* EMUI version: 4.0.1
* Launcher version: 1.1.0.1872
* Rom: Stock Rom (?)

**Comment by Frontear** [comment] 2018-03-29 18:46
Possible duplicate of #1147

**Comment by EliasSchriefer** [comment] 2018-03-29 20:02
@Frontear Yeah, you're right. Can I close this issue now?

**Comment by Frontear** [comment] 2018-03-29 22:06
No, I think its best to leave this open, since they both talk about different devices. I recommend @divadsn opinion or @deletescape. Whatever they say, close or not, is decided by them.

**Comment by divadsn** [comment] 2018-03-30 09:57
I wish I could have a device with EMUI to test that out, but @deletescape has gotten recently a hands on a Huawei device, so I am leaving that for him.

**Closed as completed** 2019-04-07 11:56 UTC
Labels: bug
